### ISSUE TITLE
Checkout form LABEL elements for attribute not properly set for country drop downs

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#1109]
At  http://www.w3.org/wiki/HTML/Elements/label W3C says 

for = string
Specified to indicate a form control with which the caption is to be associated.
The attribute's value **must be the ID** of a labelable form-associated element in the same Document as the label element.

WPeC is using other values

**Comment by JustinSainton** [comment]
Confirmed that this is built properly in 2.0.
