### ISSUE TITLE
WPEC 3.8.14.1 - Shipping to multiple target markets

### ISSUE THREAD

**Issue by jfheath** [wp-e-commerce/WP-e-Commerce#1370]
I have just upgraded to WPEC 3.8.14.1.

We are shipping to 2 target markets, and all this worked fine previously.  now, the regions for the second target market is not displayed on checkout, and shipping options cannot be selected.

Checkout is impossible

**Comment by JustinSainton** [comment]
Closing this out as unconfirmed.  The original report was unclear and the website is no longer using WP eCommerce.
