### ISSUE TITLE
A bare product is added to the cart when the selected variation combination is unavailable

### ISSUE THREAD

**Issue by jbeales** [wp-e-commerce/WP-e-Commerce#1373]
Best illustrated with a hypothetical example:

I sell shirts. They're available in Small, Medium, and Large, and Red, Green, and Blue. My manufacturer is a bit strange and refuses to make Blue shirts in Medium. 

In WPEC I have a product called "Shirt," it has variations for size & colour, and I have deleted the Medium Blue option. If a customer tries to choose a Medium Blue shirt with the select fields a message is displayed saying that combination of variants is not available, but they can still add the product to the cart, and when it's added, it's added as "Shirt," not "Medium Blue Shirt," just "Shirt."

If something's not available we shouldn't allow it to be added to the cart.

**Comment by pixelnix** [comment]
+1, needs to be fixed.

**Comment by misulicus** [comment]
Wasn't this something that was related to the wpec theme files? I recall something with grid view mode

**Comment by JustinSainton** [comment]
Confirmed this fails in both 1.0 and 2.0 theme engines.
