### ISSUE TITLE
wpsc_get_terms_category_sort_filter() produces many request if you have a lot of terms.

### ISSUE THREAD

**Issue by benhuson** [wp-e-commerce/WP-e-Commerce#1389]
The offending line is 46 in https://github.com/wp-e-commerce/WP-e-Commerce/blob/8e0a4dbe5b470bf959d838afa9ac5ba4cc50a16f/wpsc-includes/category.functions.php:

```
$term_order = ( $term->taxonomy == 'wpsc_product_category' ) ? wpsc_get_meta( $term->term_id, 'sort_order', 'wpsc_category' ) : null;
```

This gets meta for each term as they are looped through.

It might be better if we able to get all meta values from an array of terms in one query perhaps so they are cached, rather than many requests?

**Comment by JustinSainton** [comment]
Related: #1894

**Comment by benhuson** [comment]
So, now we should be able to resolve this using the new wpsc_update_meta_cache(),

See Country meta for an example:
https://github.com/wp-e-commerce/WP-e-Commerce/commit/845e287fd945477dc8b4ff765509766d52fa249c
