### ISSUE TITLE
"Show Subcategory Products in Parent Category" setting not working

### ISSUE THREAD

**Issue by benhuson** [wp-e-commerce/WP-e-Commerce#1416]
I've just done a big WP/WPEC upgrade to an old store and discovered the "Show Subcategory Products in Parent Category" setting is not working. Sub products are always show even if this is not selected.

Debugging the WP_Query I found that the "tax_query" query always has "include_children" set to 1.

A bit more investigation I found a related WordPress ticket in Trac:
https://core.trac.wordpress.org/ticket/18703

We need to add a filter to get round this...

**Comment by instinct-ray** [comment]
Sorry for the late response. I think this is fixed as I am seeing the following http://dl.getdropbox.com/u/1184399/Jing/2015-04-07_1303.png 

Thanks @benhuson
