### ISSUE TITLE
wpsc_the_product_price() doesn't respect the $no_decimals parameter if there are variations

### ISSUE THREAD

**Issue by jbeales** [wp-e-commerce/WP-e-Commerce#1432]
In the function `wpsc_the_product_price()` (in template-tags.php), when there are variations, (`wpsc_product_has_variations()` returns true), the output is generated by calling `wpsc_product_variation_price_from()` and there's no direct way to tell `wpsc_product_variation_price_from()` not to put zeros after the decimal place.

What we could do is set the `wpsc_modify_decimals` filter to a function that returns zero, (there might be one built into WP), right before calling `wpsc_product_variation_price_from()` and taking the filter off right after `wpsc_product_variation_price_from()` returns its value.

**Comment by JustinSainton** [comment]
As #1572 has been merged, this should be fixed.

@jbeales @benhuson can you both test?
