### ISSUE TITLE
Issue with removing a pre_get_posts hook within itself

### ISSUE THREAD

**Issue by bradyvercher** [wp-e-commerce/WP-e-Commerce#1444]
The `wpsc_split_the_query()` hook is being [removed from within itself](https://github.com/wp-e-commerce/WP-e-Commerce/blob/d9ca9a33329f50d0bab303ca52d33f4a2271a4af/wpsc-components/theme-engine-v1/helpers/query.php#L396), which causes any hooks attached at the next priority to be skipped. The [bug originates in WP](https://core.trac.wordpress.org/ticket/21169), but modifying the implementation in WP eCommerce will help prevent a few headaches.

While [writing a hotfix](https://core.trac.wordpress.org/ticket/21169), I came up with a couple of possible solutions. Either:

1. Attach a dummy hook just after `wpsc_split_the_query()` is registered so that at least two callbacks exist at the same priority: `add_filter( 'pre_get_posts', '__return_null', 8 );`

2. Or move the `remove_filter()` call from `wpsc_split_the_query()` to a `template_redirect` hook so that it's only fired for the main query.

**Comment by JustinSainton** [comment]
This commit seems to have broken some search layouts for different themes.

**Comment by JustinSainton** [comment]
Reverting this for 3.9.2.  It is causing more weird, obscure, hard to replicate bugs than it fixes.  If people want to add the `add_filter( 'pre_get_posts', '__return_null', 8 ); ` to a functions.php file or plugin - they can, and should, if it's causing them problems.

Until then, we'll revert and wait for [WP17817](https://core.trac.wordpress.org/ticket/17817) to land, hopefully in 4.3.
