### ISSUE TITLE
Generate $view_labels from purchlog statuses, add filter

### ISSUE THREAD

**Issue by timstl** [wp-e-commerce/WP-e-Commerce#1525]
This is in reference to pull request #1422. Apologize for the delay in getting back to this.

I'd like to find a way to generate $view_labels from the global $wpsc_purchlog_statuses to accommodate any custom statuses and label changes that are made with the wpsc_set_purchlog_statuses filter. 

I'm currently using my proposed solution from the pull request, but it needs to be improved because "the i18n functions in WordPress are not intended to be used with variables, but rather, strings." Would something as simple as using PHP's strval function on the labels work, or is another approach needed entirely?

Thanks,

Tim

**Comment by JustinSainton** [comment]
@leewillis77 just confirming - this is closed now, via #1724?

**Comment by leewillis77** [comment]
Yes, any additional statuses added via the wpsc_set_purchlog_statuses will have view labels generated for them automatically (If there are orders in that status).

This will use a default translation if none is provided in the array. To achieve a custom label, you can provide a 'view_label' entry in the wpsc_purchlog_statuses array - I've not got an example to hand, but will post one later today.

**Comment by timstl** [comment]
I am seeing one issue. I have a plugin setup that is modifying the statuses. I had previously modified my 3.8 build to incorporate a fix for this. This plugin runs on wpsc_pre_load. The dropdowns in the sales log are successfully modified. However, the status nav at the top appears not to change.

Here is my modified 3.8 build:
![Modified 3.8 build](https://dl.dropboxusercontent.com/u/58812/modified_3.8.png)

vs up-to-date 3.9 build. This should include a "Canceled" status (I have test sales set to Canceled):
![3.9](https://dl.dropboxusercontent.com/u/58812/3.9.png)

I will be digging through 3.9 today to figure out what is different, and if the problem is just on my end. Maybe I should be using a different filter? Will update with more information when I have it.

Thanks for getting this into WP E-Commerce, it's really helpful.

**Comment by timstl** [comment]
Removed my previous comment. Misunderstood. Seems to be working for me as well. Thanks for getting this into WP E-Commerce!
