### ISSUE TITLE
Multiple PayPal Payments Gateways Not Working Together

### ISSUE THREAD

**Issue by jdinsmore** [wp-e-commerce/WP-e-Commerce#1555]
When having PayPal Express Checkout 2.0 and PayPal Pro 2.0 both turned on, we've found the following: 

- If the user clicks the "PayPal" radio button, then clicks purchase, the checkout page just refreshes and the user is not re-directed to PayPal. 

If we only have PayPal Express Checkout 2.0 active, then there are no radio buttons, just a purchase button. In this case the user is successfully redirected to PayPal. Likewise, if we just have Pro 2.0 turned on, the user can input Credit Card data and successfully purchase. 

The issue appears to be when both gateways are turned on. The reason we want both options is because we want the user to have the choice to either use PayPal or pay with Credit Card directly on the site.

**Comment by JustinSainton** [comment]
Just tested Express + Standard (3.0) - worked as expected. Testing Pro now (New theme engine only.  we won't be fixing these bugs in the old theme engine.)

**Comment by JustinSainton** [comment]
No longer experiencing this issue in the new theme engine.
