### ISSUE TITLE
Improve flexibility of duplicating a product with/without images.

### ISSUE THREAD

**Issue by benhuson** [wp-e-commerce/WP-e-Commerce#1672]
The `wpsc_duplicate_product_attachment` filter (#1671) relates to the attachment files attached to the product (post). It currently doesn't provide control over product image IDs stored in meta such as the featured image and '_wpsc_product_gallery'.

This could be address via new `wpsc_duplicate_product_image` and `wpsc_duplicate_product_featured_image` filters.

Currently, if you duplicate a product with a featured image but use the `wpsc_duplicate_product_attachment` filter to opt not to duplicate the attachment files, the featured image meta will still be copied and will reference the featured image ID of the product being duplicated. The '_wpsc_product_gallery' meta is also still copied.

Possibly future enhancements also include prompting a user whether they want to duplicate images when they click the duplicate product link.

See related: #1661

**Comment by JustinSainton** [comment]
Punting to 4.1, unless you think you'll have time for this, @benhuson?

**Comment by benhuson** [comment]
When #1929 is merged this ticket can be closed.

I've set up a new issue for tackling `_wpsc_product_gallery `.

**Comment by JustinSainton** [comment]
Awesome, thanks @benhuson!
