### ISSUE TITLE
Sanity check PayPal Pro and PayPal Express Checkout 3.0

### ISSUE THREAD

**Issue by JustinSainton** [wp-e-commerce/WP-e-Commerce#1697]
Not ready for primetime, it seems.

- [x] Need to actually show both 2.0 and 3.0 PayPal Pro, change 3.0 to PayPal Pro Hosted
- [x] Hosted Pro and Express Checkout are currently not functional in either the 1.0 or 2.0 theme engine.  Current recommendation: Pull and refine for 4.0.

**Comment by omarabid** [comment]
@JustinSainton 
Is this ticket still relevant?

**Comment by JustinSainton** [comment]
Need to confirm with the support guys on this one as well.

**Comment by edoriv** [comment]
TE2 TESTS

Paypal Pro 3
Takes a bit long to load up the forms same when clicking purchase really think there needs to be a wait indicator there so people don't wind up refreshing or hitting pay again

IPN did not work when paying using PayPal (IPN is enabled)
IPN does work when paying by credit card
(additionally IPN did work when trying the PayPal 2 version)

Paypal Express worked and correctly set the transaction result

Digital Goods Worked (side note the process opens a new window... this might not be so great on mobile devices will need to try it)

**Comment by misulicus** [comment]
Just tried to test PRO hosted.
Clicked checkout, got a weird looking page where i can select to pay with account or by card. picked card and entered paypal test card and i get

```
Bad Request

Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.
Cookie
/n
```

**Comment by misulicus** [comment]
Express checkout 3.0 fails when using a coupon in my tests.
I always get this:
The totals of the cart item amounts do not match order amounts

**Comment by misulicus** [comment]
Isssue with pro gateway and coupon:
https://dl.dropboxusercontent.com/u/16683640/Screenshots/2015-01-20_0035.png

Paypal shows:
https://dl.dropboxusercontent.com/u/16683640/Screenshots/2015-01-20_0037.png

**Comment by omarabid** [comment]
@misulicus Regarding https://github.com/wp-e-commerce/WP-e-Commerce/issues/1697#issuecomment-70338750 , it's a PayPal Cookies issue and the only way to fix it is to clear the PayPal related cookies.

@edoriv Are you testing on a local site, or a remote site?

**Comment by edoriv** [comment]
@omar the site is online it's our test site http://test.wpecommerce.org

**Comment by omarabid** [comment]
@misulicus @edoriv @JustinSainton 

Can we do final tests and close this? (or report bugs here)

**Comment by omarabid** [comment]
Coupon code was fixed here: https://github.com/omarabid/WP-e-Commerce/commit/71e41b0703a762c32c8b040eba584afb7cfafaa4
