### ISSUE TITLE
Check responses on AJAX methods for helpful filters.

### ISSUE THREAD

**Issue by JustinSainton** [wp-e-commerce/WP-e-Commerce#1698]
Related: https://wordpress.org/support/topic/stock-count-not-working-after-updating-to-v39-of-plugin?replies=9#post-6302675

It's sort of lame that our AJAX responses - at least the ones with custom js events - are not all filterable.

**Comment by benhuson** [comment]
Missing a curly brace in if statement?
https://github.com/wp-e-commerce/WP-e-Commerce/commit/6daf1b0d2f9a7805215138ae4b9057504d27cac7#diff-3a14437c233179464bc81aeb3a543e0fR1113
