### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by jtsternberg** [wp-e-commerce/WP-e-Commerce#1709]
CMB2's version for reference.
https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md

**Comment by NikV** [comment]
I would be willing to help write some initial stuff.

**Comment by JustinSainton** [comment]
By all means, that would be awesome!

**Comment by JustinSainton** [comment]
Prior art:

https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/CONTRIBUTING.md

**Comment by NikV** [comment]
Awesome, pushing straight to master too, correct?

**Comment by JustinSainton** [comment]
Straight up.

**Comment by NikV** [comment]
Awesome, fresh CONTRIBUTING.md coming right up!

**Comment by NikV** [comment]
WIP PR here: https://github.com/wp-e-commerce/WP-e-Commerce/pull/1857
