### ISSUE TITLE
Calculation of taxes logic has a "bug"

### ISSUE THREAD

**Issue by 1bigidea** [wp-e-commerce/WP-e-Commerce#1712]
In my client site, we force country/state (since all orders are picked up on site). With the upgrade to 3.9.1 - our tax calculation stopped working.

I have tracked it down to lines 150 & 183 in /wpsc-taxes/controllers/taxes_controller.class.php - the logic tests for the presence of a meta field "wpec_taxes_taxable". It does not however check the value of the field. 

No amount of jumping up and down on my product will make the wpec_taxes_taxable disappear from the meta - the value merely toggles from "on" to ""(empty).

It seems that we should be testing the value also. 

I'll attach a pull request shortly for review.

**Comment by jbeales** [comment]
So, who do I yell at for this not being released, at least as some sort of 3.9.1.1 urgent bug-fix or something? 

This is the kind of thing that causes accounting nightmares for store owners, and causes developers to loose lots of time tracking down a known, and fixed 3 months ago, but not released, bug.

**Comment by JustinSainton** [comment]
:hand:

**Comment by jbeales** [comment]
I figured it was you ;) Maybe there should be a discussion around frequent bug-fix releases, especially ones that affect accounting.

**Comment by instinct** [comment]
Agreed. It's good for community but we need you to help keep an eye on things too :)

**Comment by JustinSainton** [comment]
:+1: to any discussion around bug-fix frequency.
