### ISSUE TITLE
Use global statuses for order bulk actions

### ISSUE THREAD

**Issue by bekarice** [wp-e-commerce/WP-e-Commerce#1723]
Suggestion: Order statuses are coded into the global $wpsc_purchlog_statuses (which is filterable), but then these aren't used for the bulk actions. Instead, the bulk actions are [hard-coded here](https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-admin/includes/purchase-log-list-table-class.php#L564).

Seems like using the purchase log statuses to create the actions would make this more flexible & make it easier to add custom statuses.

**Comment by JustinSainton** [comment]
Yes!  Totally agree.  Semi-related: #1525.

**Comment by bekarice** [comment]
Gotcha, missed that one :)

**Comment by JustinSainton** [comment]
No worries - great to have them both, as they're definitely intertwined.
