### ISSUE TITLE
Sales Log Totals Incorrect

### ISSUE THREAD

**Issue by jdinsmore** [wp-e-commerce/WP-e-Commerce#1728]
In WP-Admin the "Sales Log" page (i.e. Store Sales in LHN) displays a Total count of Items and dollar amounts, both in the top right and bottom right corners (e.g. 4 items - Total (excluding Incomplete and Declined) $100.00)

In our example we have the following 4 sales:
ID/Amount/Status
48/$584.98/Job Dispatched
47/$186.94/Job Dispatched
46/$38.48/Job Dispatched
45$47.79/Closed Order

The Computed totals in the top right/bottom right are showing as follows:
4 items - Total (excluding Incomplete and Declined): $810.40

While we do have 4 items, the total of those items should be: $518.19

There is a difference of $47.79 between the actual total and the total shown on screen. Coincidentally, the one sale with a Status of "Closed Order" has an amount of $47.79. 

![saleslogo](https://cloud.githubusercontent.com/assets/2574455/5705881/67f71692-9a4a-11e4-9346-aaebacf428ca.jpg)

**Comment by misulicus** [comment]
From what i can tell the Amount is correct except its not counting Closed Order one.
It should show 858.19 which is the total of your sales since you have no incomplete/declined ones

**Comment by jdinsmore** [comment]
I agree that the calculation for Total amount doesn't appear to be including the amount of the closed order, hence the Amount is incorrect.

**Comment by misulicus** [comment]
This should be the fault https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-admin/includes/purchase-log-list-table-class.php#L183
