### ISSUE TITLE
Force SSL on checkout affects admin.

### ISSUE THREAD

**Issue by misulicus** [wp-e-commerce/WP-e-Commerce#1730]
Tested on master.
Enable force ssl on checkout settings and then try to open Pages menu. It will fail to load if you don`t have SSL installed.

**Comment by misulicus** [comment]
i think the problem seems to be inside function wpsc_force_ssl()

**Comment by JustinSainton** [comment]
Works fine for me.

**Comment by misulicus** [comment]
Make sure you test on a store with no ssl. I double checked when that option is enabled the pages menu directs to https

**Comment by JustinSainton** [comment]
Still haven't been able to replicate this.  Will await a second opinion here.
