### ISSUE TITLE
Google Analytics ecommerce tracking + Yoast's plugin is broken

### ISSUE THREAD

**Issue by ablears** [wp-e-commerce/WP-e-Commerce#1736]
Not sure if you can do anything about this. Thanks to [this commit] (https://github.com/Yoast/google-analytics-for-wordpress/commit/bcd70a62e1670516246244d67ef7f3dc505342e3) Yoast's Google Analytics for Wordpress now uses '__gaTracker' not 'ga'. 

That means ecommerce transactions will error with 'Uncaught ReferenceError: ga is not defined'

**Comment by JustinSainton** [comment]
To clarify, it seems this would only fail when using universal analytics, is that right?

I wonder if something like this, [added here](https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-includes/google-analytics.class.php#L92), would do the trick?

`var ga = typeof ga === 'undefined' && typeof __gaTracker !== 'undefined' ? __gaTracker : ga;`

**Comment by ablears** [comment]
That looks like it would work. The other thing I was thinking, to be as flexible as possible, is to provide a free text box as an advanced setting. That way we could set whatever handler we needed.

**Comment by JustinSainton** [comment]
@ablears Sure, I could see the value in that.  Though, at the point that we're just passing through a text box, we could basically just set the Tracking Code Present box and allow users to set the code in their header.php.  I have a particularly bad allergic reaction to new settings.

**Comment by galbaras** [comment]
@JustinSainton and @ablears, I think it would be much simpler to change the code from using "ga", which is outdated and doesn't work, to using "__gaTracker", which works.

In the meantime, I've placed the following code at the top of the wpsc-transaction_results.php within my theme:

<script type="text/javascript">
	var ga = typeof ga === "undefined" && typeof __gaTracker !== "undefined" ? __gaTracker : ga;
</script>

**Comment by benhuson** [comment]
I prefer the @JustinSainton way of handling fallback for older tracking code if possible. Updating tracking codes tends to be one of those things that often gets missed and there could be a lot of people not using the latest tracking code.

I recently saw some JavaScript code in a project I was working on with fallbacks all the way to urchinTracker() for tracking page views ;)

Not sure that it's the best structured if statement in the world but back-compatibility is good.

```
if (typeof urchinTracker == FUNCTION) 
    urchinTracker(value);
if (typeof pageTracker != UNDEFINED && typeof pageTracker._trackPageview == FUNCTION)
    pageTracker._trackPageview(value);
if (typeof _gaq != UNDEFINED && typeof _gaq.push == FUNCTION)
    _gaq.push(['_trackPageview', value]);
if (typeof ga == FUNCTION) 
    ga('send', 'pageview', value);
```

**Comment by galbaras** [comment]
@benhuson, your code seems to miss the most important function: __gaTracker. That's the correct one to use. Still, you point about backward compatibility is valid.

I've actually used the code proposed by @JustinSainton, which ensures backward compatibility with "ga". I've just placed it in a theme file, instead of the plugin, to protect it from being overwritten by plugin updates.

**Comment by galbaras** [comment]
I can confirm that the following works:

If needed, copy the file wpsc-transaction_results.php to the active theme directory. Then, edit it and add the following code between the closing PHP tag (?>) and the DIV tag:

<script type="text/javascript">
	var ga = typeof ga === "undefined" && typeof __gaTracker !== "undefined" ? __gaTracker : ga;
</script>

**Comment by benhuson** [comment]
@galbaras Yep, was aware it wasn't fully up-to-date, but just interesting to see fallbacks all the way back to urchin :)
