### ISSUE TITLE
Changing from 2.0 to 1.0 breaks URLs

### ISSUE THREAD

**Issue by omarabid** [wp-e-commerce/WP-e-Commerce#1738]
I changed from t.e. 2.0 to t.e. 1.0 by changing the permalink structure. If I try to update or checkout on the checkout form, it seems to be still using the old permalink structure which makes the checkout impossible.

New Checkout Path: ?page_id=5

Error message you get when you try to checkout or update the cart:

```
Not Found

The requested URL /products-page/checkout/ was not found on this server.
```

**Comment by JustinSainton** [comment]
This appears to be fixed now.  @omarabid, can you confirm?
