### ISSUE TITLE
Fatal error: WPSC_Countries::get_countries(): 

### ISSUE THREAD

**Issue by tcg89** [wp-e-commerce/WP-e-Commerce#1758]
I get the following fatal error message on my e-commerce site at random times during the night. 
I have deactivated all plugins and fired them up 1 x 1 to see if there's any incompatibility issues; none found. Everything else works like its suppose to, but when you turn off shipping, that's when the error stops; i have to charge for shipping. I am also using the gold cart plugin on the most recent version so i know that's not the problem. I have already used my one-time support key to have the good people at getshopped.org look at it and they found nothing, checked the country/tax region table and everything checked out. 

This error message basically appears on my site making it unusable till i login to admin panel and deactivate then reactivate wp e-commerce, and the site returns to normal. 

Fatal error: WPSC_Countries::get_countries(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;WPSC_Data_Map&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in /home/content/p3pnexwpnas05_data03/43/2372243/html/wp-content/plugins/wp-e-commerce/wpsc-includes/wpsc-countries.class.php on line 462

Fatal error: WPSC_Countries::_dirty(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;WPSC_Data_Map&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in /home/content/p3pnexwpnas05_data03/43/2372243/html/wp-content/plugins/wp-e-commerce/wpsc-includes/wpsc-countries.class.php on line 1142

**Comment by JeffPyeBrook** [comment]
It's my guess that what is happening is that there is a corrupted copy of the serialized object stored in the WordPress cache or a transient.  Any chance you can check to be sure that either of these isn't happening?

**Comment by tcg89** [comment]
Any step by step instruction on how I could do that?

**Comment by tcg89** [comment]
I downloaded transient cleaner plugin and they were about 35 Transients and 0 have expired. It's now down to 5 timed transients.

**Comment by JustinSainton** [comment]
We've determined this to be a GoDaddy-specific issue.  Deleting the /wp-content/object-cache.php file until they move to Memcached instead of APC (possibly happening, at some point) or we move to a different data layer for countries (#1865) will do the trick.
