### ISSUE TITLE
Security issue or false positive on PayPal Standard payment gateway settings

### ISSUE THREAD

**Issue by TimSmith** [wp-e-commerce/WP-e-Commerce#1759]
WordPress 4.1, WP E-commerce 3.9.1 on Apache
PC with Firefox 35.0.1, with Kaspersky AntiVirus 15.0.1.415(b) and Kaspersky Firefox Extension Dangerous Website Blocker plugin 4.5.3.8

In the WP admin, Settings, Payments tab if you click on Settings under PayPal Payments Standard 2.0 then Kaspersky blocks the request. It's message is Dangerous URL blocked;http://domain/wp-admin/admin-ajax.php;http://domain/wp-admin/admin-ajax.php;Heuristic Analysis;Firefox;

Curiously none of the other payment gateways settings links cause this behaviour, I guess this one does something different. As opening the PayPal Standard settings in another browser tab works fine I presume it's a false positive.  Assuming it is a false positive I think you'll get more traction with reporting the issue to Kaspersky then I will as you can be authorative about what the page is doing.

**Comment by JeffPyeBrook** [comment]
I use Kaspersky and have seen this message from time to time, especially on my development sites.  My vague recollection for the live sites is that setting the administration to be over https eliminated the warning.

**Comment by TimSmith** [comment]
That's unfortunately not an option as the client doesn't use SSL. It's more than a warning too as it blocks that section from opening up on the page.

**Comment by JustinSainton** [comment]
Closing this out, as I'm not certain there is anything for us to change here.
