### ISSUE TITLE
Documentation is not accessible

### ISSUE THREAD

**Issue by rogersmj** [wp-e-commerce/WP-e-Commerce#1765]
https://wpecommerce.org/
http://docs.wpecommerce.org/
http://getshopped.org/

These have all been down for days, making the documentation inaccessible. Any word on when the site might be available again?

**Comment by misulicus** [comment]
Both docs and wpecommerce.org work just fine here. Try flushing cache

**Comment by instinct-ray** [comment]
Second to mihai comment. Wpecommerce.org and docs are working fine.

**Comment by rogersmj** [comment]
That's weird, tried on a couple different machines in different locations and couldn't get them to come up. Now they are. Never mind then...closing.
