### ISSUE TITLE
Can we push out bug-fix releases more frequently?

### ISSUE THREAD

**Issue by jbeales** [wp-e-commerce/WP-e-Commerce#1796]
I commented on #1712 that I wasn't happy it had already been fixed, 3 months ago, and not released to the public. This particular bug stops tax from being calculated, and charged, on stores that don't charge shipping, and maybe on stores that charge flat-rate shipping - which is an accounting and legal nightmare for business owners.

I believe we should push out bug-fix changes quickly. I realize that we don't want to create upgrade fatigue, but sitting on bug fixes isn't right either, so let's have a discussion about how we can make this work. Here are a couple of ideas:

1. When a production-ready bug fix is merged, like #1712, start a timer, and make a bug-fix release within 5-7 days of fixing it. If we can fit a few more bug fixes into the same release then great, (hence the timer instead of releasing immediately).

2. Alternately, make a policy that bug-fix releases should be 100% non-breaking and push them out as they're ready, (probably as 0.0.0.x releases). This would work especially well if we have an automated release process to get code from GitHub tags to WP SVN tags. We may have a trust issue with this, many WPeC releases have come out buggy, or with a lot of backward-incompatibility, but this might be a way to re-build trust.

Both of these approaches bring up the question of where to commit bug fixes and manage the faster release cycle. I'm not sure what the current strategy is for managing our branches. If `master` is always stable then these questions might not matter:

* Do bug-fix commits go into a production-ready bug-fixes branch, with changes merged into `master` and bug-fix releases are tagged off of it? 
* Do bug-fix commits go into `master` but we somehow keep track of which ones will go into the next bug-fix release, then cherry-pick commits into a release?

Discuss.

**Comment by instinct** [comment]
I'm very keen for you to help us out with these types of releases. 

With a release must come a blog post and a range of other small PR related activities, so if you can help with those too then I'm happy to add you to our trello account and get some in between major release action happening.

d

**Comment by JustinSainton** [comment]
@jbeales Great thoughts; here are a few of my own:

* 100% on board with more frequent bug/maintenance/security-type releases.  In theory, we'd have a minor release like that every 2-4 weeks, or more frequently if we screw something up on a major release.
* 3.9.2. should have gone out with the tax fix (and a few others) awhile ago.  It hasn't, and we need to fix that.
* We won't ever have x.x.y.z releases again.  Any minor release that comes out would be x.x.y
* As soon as a major release comes out (like 3.9), master immediately becomes the next major release - trunk, master, etc. is effectively 4.0.  At the same time, we need to clone a branch from the previous major release and have it as the next dot-release.  Then, when commits/PRs are merged into master that fix security/maintenance/bug fixes that are low-risk and worthy of a dot-release, they should be cherry-picked into that branch.

Make sense?

**Comment by jbeales** [comment]
Sorry for the slow response.

@JustinSainton Those points make sense.

How should we be keeping track of the fixes that will go into the bug-fix releases? Can we tag the issues or pull requests in GitHub?

@instinct I'm often very busy, but let's see if we can make this work. I would like to help help get bug-fixes out to WPeC store owners and maintainers, (including myself). I'll try to keep these releases very conservative so nothing breaks. I think I have your E-mail somewhere so I'll drop you a line to get added to Trello.

**Comment by JustinSainton** [comment]
Yep, anything going into 3.9.2. should be in the [3.9.2 milestone](https://github.com/wp-e-commerce/WP-e-Commerce/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.9.2).
