### ISSUE TITLE
Gold Cart Throwing Errors Referencing Variable

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#1804]
[17-Mar-2015 13:24:09 UTC]
error type: [2] in_array() expects parameter 2 to be array, string given file: /home/sparkle_sites/sparkle-gear.com/wp-content/plugins/gold-cart_plugin-2.9.7.8/gold_shopping_cart.php line: 477
[17-Mar-2015 13:24:09 UTC] Debug Trace:
...
...gold_shopping_cart.php at line 477 function n/a (?, 1=529062)
....wpsc-products_page.php at line 91 function n/a (?)
.....page.php at line 977 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-conte...)
......page.php at line 664 function n/a (0=grid)
.......page.php at line 686 function n/a (0=[productspage])
........n/a at line n/a function n/a (0=West Liberty Custom Basketball Shirt.

Spec...)
.........plugin.php at line 213 function n/a (?)
..........post-template.php at line 221 function n/a (0=the_content, 1=West Liberty Custom Basketball...)
...........entry-content.php at line 18 function n/a (0=Read more)
............template.php at line 503 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-conte...)
.............template.php at line 477 function n/a (?)
..............general-template.php at line 171 function n/a (?)
...............content-page.php at line 37 function n/a (0=partials/entry, 1=content)
................template.php at line 503 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-conte...)
.................template.php at line 477 function n/a (?)
..................general-template.php at line 171 function n/a (?)
...................page.php at line 26 function n/a (0=partials/content, 1=page)
....................page.php at line 1032 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-conte...)
.....................n/a at line n/a function n/a (0=)
......................plugin.php at line 496 function n/a (?)
.......................template-loader.php at line 12 function n/a (0=template_redirect)
........................wp-blog-header.php at line 16 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-inclu...)
.........................index.php at line 17 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-blog-...)

[17-Mar-2015 13:24:09 UTC]
error type: [2] in_array() expects parameter 2 to be array, string given file: /home/sparkle_sites/sparkle-gear.com/wp-content/plugins/gold-cart_plugin-2.9.7.8/gold_shopping_cart.php line: 477
[17-Mar-2015 13:24:09 UTC] Debug Trace:
...
...gold_shopping_cart.php at line 477 function n/a (?, 1=529062)
....wpsc-products_page.php at line 91 function n/a (?)
.....page.php at line 977 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-conte...)
......page.php at line 664 function n/a (0=grid)
.......page.php at line 686 function n/a (0=[productspage])
........n/a at line n/a function n/a (0=West Liberty Custom Basketball Shirt.

Spec...)
.........plugin.php at line 213 function n/a (?)
..........post-template.php at line 221 function n/a (0=the_content, 1=West Liberty Custom Basketball...)
...........entry-content.php at line 18 function n/a (0=Read more)
............template.php at line 503 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-conte...)
.............template.php at line 477 function n/a (?)
..............general-template.php at line 171 function n/a (?)
...............content-page.php at line 37 function n/a (0=partials/entry, 1=content)
................template.php at line 503 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-conte...)
.................template.php at line 477 function n/a (?)
..................general-template.php at line 171 function n/a (?)
...................page.php at line 26 function n/a (0=partials/content, 1=page)
....................page.php at line 1032 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-conte...)
.....................n/a at line n/a function n/a (0=)
......................plugin.php at line 496 function n/a (?)
.......................template-loader.php at line 12 function n/a (0=template_redirect)
........................wp-blog-header.php at line 16 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-inclu...)
.........................index.php at line 17 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-blog-...)

[17-Mar-2015 13:24:09 UTC]
error type: [2] in_array() expects parameter 2 to be array, string given file: /home/sparkle_sites/sparkle-gear.com/wp-content/plugins/gold-cart_plugin-2.9.7.8/gold_shopping_cart.php line: 477
[17-Mar-2015 13:24:09 UTC] Debug Trace:
...
...gold_shopping_cart.php at line 477 function n/a (?, 1=529062)
....wpsc-products_page.php at line 91 function n/a (?)
.....page.php at line 977 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-conte...)
......page.php at line 664 function n/a (0=grid)
.......page.php at line 686 function n/a (0=[productspage])
........n/a at line n/a function n/a (0=West Liberty Custom Basketball Shirt.

Spec...)
.........plugin.php at line 213 function n/a (?)
..........post-template.php at line 221 function n/a (0=the_content, 1=West Liberty Custom Basketball...)
...........entry-content.php at line 18 function n/a (0=Read more)
............template.php at line 503 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-conte...)
.............template.php at line 477 function n/a (?)
..............general-template.php at line 171 function n/a (?)
...............content-page.php at line 37 function n/a (0=partials/entry, 1=content)
................template.php at line 503 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-conte...)
.................template.php at line 477 function n/a (?)
..................general-template.php at line 171 function n/a (?)
...................page.php at line 26 function n/a (0=partials/content, 1=page)
....................page.php at line 1032 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-conte...)
.....................n/a at line n/a function n/a (0=)
......................plugin.php at line 496 function n/a (?)
.......................template-loader.php at line 12 function n/a (0=template_redirect)
........................wp-blog-header.php at line 16 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-inclu...)
.........................index.php at line 17 function n/a (0=/home/sparkle_sites/sparkle-gear.com/wp-blog-...)

**Comment by JustinSainton** [comment]
Will be fixed in upcoming 2.9.8 release.  cc: @misulicus.
