### ISSUE TITLE
pulling all that form and logic out of templates

### ISSUE THREAD

**Issue by curtismchale** [wp-e-commerce/WP-e-Commerce#1815]
As I'm working on a plugin I'd love to have a buy button for products in my custom displays. Unfortunately as I've been looking around it would seem I need to copy the whole damn form out of the theme engine to make sure I accommodate every product type possible.

I'd love to have a single function `wpsc_get_product_form` which you could pass a product_id (or variation_id if you just want to purchase a variation with the selections for the variation_id) and then the form would figure itself out and return/echo.

This would cut a bunch of logic from the theme templates (which I something I've been complaining about for a while http://curtismchale.ca/2011/03/01/wp-e-commerce-a-theme-developers-nightmare/) and make it so that future theme developers could include a single function and know that their product purchase forms are maintained in core without constant revisiting.

This may take the form of a new class or just  a template tag (or set of template tags). This would also let us update and build out testing around the forms since we'd theoretically have a bunch of small testable units of code for each product type.

Good idea? Bad idea? Discussion had already that I didn't find in current Github issues?

**Comment by curtismchale** [comment]
So justin pointed out the Theme Engine V2 which makes this redundant.

Lets get 4.0 out faster.

**Comment by instinct** [comment]
Careful, you'll start to sound like me soon.

But yes... let's get it out there!!! I'm hoping Justin will have it ready this month ;)

d

**Comment by curtismchale** [comment]
What @instinct I thought @JustinSainton was going to have it ready Monday. :)

**Comment by JustinSainton** [comment]
Back to your cubicles, both of you. @instinct @curtismchale
