### ISSUE TITLE
replacing/adding method in WPSC_Controller_Customer_Account

### ISSUE THREAD

**Issue by curtismchale** [wp-e-commerce/WP-e-Commerce#1821]
Jumping off https://github.com/wp-e-commerce/WP-e-Commerce/issues/1820 once you can filter here and add a link.

How is one supposed to ... actually add content to the page. If I go ahead with that change then I get:

```
Fatal error: Invalid controller method: WPSC_Controller_Customer_Account::wishlist() in /srv/www/wpec/htdocs/wp-content/plugins/wp-e-commerce/wpsc-components/theme-engine-v2/classes/router.php on line 230
```

I don't see anything in router.php, mvc.php, controller.php that would let me tell the view what I should be seeing here.

If I 'hack' core to add the expected method to WPSC_Controller_Customer_account then in theory I could get some content out to my view.

Maybe I'm just missing something here and it's obvious with someone used to MVC.

**Comment by JustinSainton** [comment]
Yeah, we need a solid way to register other controllers.  Nothing exists right now, because the `_wpsc_load_controller()` method is directly coupled to the core controllers folder.  We need to decouple that and add a way for plugins to register their own controllers.

**Comment by JustinSainton** [comment]
Alright, so I've gotten to the bottom of all of this.  I'm not 100% happy with the solution, but there are a fair amount of moving parts:

1. We need to allow the router path and class to be conditionally overridden. Commit forthcoming
1.You have to set the view in the included controller class::method.
1. You have to register an additional template path.

I'll put together a gist/sample plugin for this shortly, but I do have this effectively working.  Any thoughts on how a simple abstraction might make it easier for developers would be welcome.

**Comment by JustinSainton** [comment]
@curtismchale For reference: https://github.com/wp-e-commerce/sample-tev2-plugin

**Comment by JustinSainton** [comment]
@misulicus ^ Let's abstract what we can from the sample plugin above and add it to [the documentation](http://docs.wpecommerce.org/category/wpec-theme-engine-v2/)
