### ISSUE TITLE
TE2 Default styling

### ISSUE THREAD

**Issue by misulicus** [wp-e-commerce/WP-e-Commerce#1823]
Enabling/disabling those 2 check boxes takes few tries some times for me.
And when finally i got them disabled the main website page shows

`WARNING: D:\wamp\www\wpec-dev\wp-content\plugins\wp-e-commerce\wpsc-components\theme-engine-v2\helpers\css.php:25 - in_array() expects parameter 2 to be array, string given`

**Comment by JustinSainton** [comment]
I see what's happening here.  You can't disable them at the same time, and you can't disable or enable inline CSS without _also_ doing that with the common CSS.  It's a weird UX, but not a "bug", per se.

**Comment by JustinSainton** [comment]
@misulicus Let me know if this is resolved now, and any potential UX recommendations for further ensuring users don't try to dequeue inline without dequeuing common styles.
