### ISSUE TITLE
TE2 Remove cart item

### ISSUE THREAD

**Issue by misulicus** [wp-e-commerce/WP-e-Commerce#1824]
On the store/cart/ page with 2 items in cart for example i click Remove under one item, page refreshes, URL becomes /store/cart/remove/0/?_wp_nonce=09bcb5f0a1

The product still shows in cart but quantity is 0 and Item total = 0
Have to reopen the cart page to see the cart with just 1 item

**Comment by JustinSainton** [comment]
See: #848, specifically this note: ` Confirm cart clearing and item removal work. Initial tests failed, reviewing the code makes me think we need to redirect and we're not.`

**Comment by JustinSainton** [comment]
@misulicus Any tips on how to replicate this?  I just tried and could not.

**Comment by misulicus** [comment]
Just tested on latest master and te2
add 2 items to cart. Once on the store/cart/ page you will see 2 items in the cart. Click Remove for one of them.

**Comment by misulicus** [comment]
```
	public function remove( $key ) {
		global $wpsc_cart;

		if ( ! wp_verify_nonce( $_REQUEST['_wp_nonce'], "wpsc-remove-cart-item-{$key}" ) ) {
			wp_die( __( 'Request expired. Please go back and try removing the cart item again.', 'wpsc' ) );
		}

		$wpsc_cart->remove_item( $key );
		$this->message_collection->add( __( 'Item removed.', 'wpsc' ) );
	}
```

looking at that file i added this in above function at the end and now the page removes the item correctly and also just "reloads" the store/cart page and not the nonce`d remove url
```
wp_safe_redirect( wp_get_referer() );
exit;
```

**Comment by JustinSainton** [comment]
Hmm...this sort of weirds me out.  Only because Clear Cart works just fine.  And it doesn't redirect.  It feels like we're hiding a deeper problem.  Let me dig a bit.

**Comment by JustinSainton** [comment]
@misulicus one of the smells, you'll notice that it refreshes the page (expected), but does not show the message (unexpected)

**Comment by JustinSainton** [comment]
ahh, need to set it as a flash message.  Okay.  I'm alright with this.  I think.
