### ISSUE TITLE
wpsc_is_checkout always returns false?

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#1827]
It seems that the wp_query property "is_checkout" is never set?

**Comment by JustinSainton** [comment]
Yeah, noted here: https://github.com/wp-e-commerce/WP-e-Commerce/issues/1715#issuecomment-67813377.  The logic in that function basically always failed until 9448cbcb047eed9221f3e76bcd8b088ae70e26b4
