### ISSUE TITLE
Taxonomy wpsc_log_type showing up in site maps

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#1842]
This taxonomy is now showing up in sitemaps generated by any of the popular seo plugins .  Not sure what this taxonomy is used for, but if the post type that it applies to is not available via public query able why should this taxonomy be publicly queryable?

**Comment by JustinSainton** [comment]
Agreed, this should not a be a public taxonomy.  I'll touch base with @pippinsplugins upstream on this. I think it'd be fine to set it, like they do upstream, to the boolean of WP_DEBUG.

**Comment by JeffPyeBrook** [comment]
@justin I think this went the wrong way, exposing the post type or taxonomy to the front end is not want we want to do.  Keeping the logs from being accessed by anything on the user facing side, at all times, would seem to be a good idea.  Setting the public to false for both the taxonomy and the post type is what I would recommend.

**Comment by JeffPyeBrook** [comment]
.... i think all we need is to have an array( 'public' => false, 'show_ui' = true, 'show_in_nav_menus' => false ) as part of the arguments to the register calls

**Comment by JustinSainton** [comment]
I'm happy enough with that, though show_ui should be the WP_DEBUG boolean.

**Comment by JeffPyeBrook** [comment]
I don't think WP_DEBUG is right?  Why would we ever want someone who isn't an administrator to have access to a site's log information?

**Comment by JustinSainton** [comment]
`show_ui => true` is already going to expose the UI for everyone.  It's logging, we only want the UI exposed when debugging.

**Comment by JeffPyeBrook** [comment]
The critical issue is that the other two args are false, that will stop the post type and taxonomy from being requested by a user. 

As far as show_ui goes, the way the class is written is that it could always be logging, if you hide the ui from the administrator they would never see the data collected, or be able to clear it, unless they were debugging  If that is ok then WP_DEBUG is what you want.  The advantage to the logging class is that it lets someone see issues without going into developer mode. The paypal gateways have a checkbox that enables the collection.  If you use WP_DEBUG, then even if the store admin clicks the debug checkbox they will not be able to browser the log posts.

**Comment by JeffPyeBrook** [comment]
perhaps checking capabilities for administrator is the best answer?

**Comment by JustinSainton** [comment]
I don't think so, necessarily. I know lots of stores have situations where a store admin role exists - nearly admin, but restricted a bit just to store related pages/options.  They wouldn't pass `current_user_can( 'manage_options' )`, but they should still have access to logs.

The point you bring up about the enabling of logging through gateways is apt, though.  I think we have these args filterable, default to WP_DEBUG, and returning true via filter if gateways have enabled debugging at that granular level.

**Comment by JeffPyeBrook** [comment]
How about use 
```
wpsc_in_debug_mode()
```

**Comment by JeffPyeBrook** [comment]
Sorry,  

you might not of merged that PR

```
/**
 * Check if awe are in 'debug' mode, use if you want to conditionally output messages to the error log
 * or admistrator console
 *
 * Debug mode will be enabled if WordPress debug mode is enabled
 * Debug mode will be set if the constant WPSC_DEBUG is defined and evaluates to true
 * Debug mode can be set by a logged in administrative user by appending '?wpsc_debug_mode=1' to the end of any site url
 *
 * @return bool
 */
function wpsc_in_debug_mode() {
	$wpsc_debug_mode = false;

	// is WordPress debug mode on?
	if ( defined( 'WP_DEBUG') && WP_DEBUG ) {
		$wpsc_debug_mode = true;
	}

	// is WPeC debug mode on?
	if ( defined( 'WPSC_DEBUG') && WPSC_DEBUG ) {
		$wpsc_debug_mode = true;
	}

	// get the value of the debug mode option, if it is not defined create it so that
	// the option is cached and debug mode can be determined with greate haste
	$debug_mode_option = intval( get_option( 'wpsc_debug_mode', -1 ) );
	if( -1 == $debug_mode_option ) {
		$debug_mode_option = 0;
		update_option( 'wpsc_debug_mode', $debug_mode_option );
	}

	// has debug mode been enabled from a url request by an administrator
	if (  isset( $_REQUEST['wpsc_debug_mode'] ) ) {
		if ( funtion_exists( 'current_user_can' ) && current_user_can( 'manage_options' ) ) {
			$debug_mode_option = intval( $_REQUEST['wpsc_debug_mode'] );
			update_option( 'wpsc_debug_mode', $debug_mode_option );
		}
	}

	// has debug mode been previously enabled by an administrator request
	if ( $debug_mode_option ) {
		$wpsc_debug_mode = true;
	}

	return $wpsc_debug_mode;

}
```

**Comment by JustinSainton** [comment]
Yeah, i don't recall seeing that in a PR :hushed: 

I'm not super sure I want that right now, but am open to other thoughts on it.

**Comment by JustinSainton** [comment]
Also, show_in_nav_menus inherits public, so explicitly setting is not necessary.

**Comment by JeffPyeBrook** [comment]
It is a good way to centrally  check for diagnostics is enabled, and turn on if necessary.  I use it because I don't like to enable WP_DEBUG on a live site that isn't my own, and often the site I am working with may not have shell or ftp access knowledge.

The commit that introduced the code is https://github.com/JeffPyeBrook/WP-e-Commerce/commit/fe7c7cd905dedeb389d6c9b8a1b9b2adf6d107b0

The value returned by the function is also used to turn on and off the diagnostics  built into the WPeC javascript. It is sent via the script localization structure.

**Comment by JustinSainton** [comment]
:+1: Happy for that to stay in a branch or diagnostic plugin, as it does seem to serve it's purpose well there.

Closing this out as of 74f3ee81fbca047c5a18b28c3d4e588961a574dc

**Comment by JustinSainton** [comment]
Hmm, @JeffPyeBrook, finding that public = false, show_ui = true, still does not show the UI.

I wonder, does the site map issue persist if public = true and publicly_queryable = false?

**Comment by JustinSainton** [comment]
Sadly, it seems that at least one of the major plugins depends on public, rather than publicly queryable - so this particular issue will actually not be solved by anything proposed or suggested here. 

That said, public should be false.  We can add the submenu item manually.
