### ISSUE TITLE
Change wpsc_add_to_cart() to check $_REQUEST, rather than $_POST

### ISSUE THREAD

**Issue by JustinSainton** [wp-e-commerce/WP-e-Commerce#1852]
This allows GET requests, which will be required for an cart URL API.

The imagination is an API, something like `wpsc_get_add_to_cart_url( $args = array() )`.  One could simply pass a `WPSC_Product` object, a product id, or an array of product ids and parameters to the function.  It would return a URL containing either the query args, or a hash, or something.  Haven't fully thought through the implications there for nginx configs, entity-too-large errors, etc.  The idea, though, is that an abstracted layer allows us to sort that out at a lower level.  Will file a separate ticket on that

**Comment by JustinSainton** [comment]
Worth noting, this change *will break* for anyone doing hacky things like forcing POST variables and expecting them to also be set as REQUEST variables.

We should document this change

Related: #1891.

**Comment by leewillis77** [comment]
Thank you for your notes. Hacky things updated :)

**Comment by JustinSainton** [comment]
:+1:
