### ISSUE TITLE
Gold Cart Generating a 404 on a background image

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#1871]
Looks like the relative path to **images/outofstock.png** isn't working because the CSS is coming from a CSS directory

(404) .../wp-content/plugins/gold-cart_plugin-2.9.7.8/css/images/outofstock.png

```
.product_grid_display p.soldout, #content .product_grid_display p.soldout {
	font-weight:bold;
	font-size:14px;
	color:#C33;
	background:url(images/outofstock.png) no-repeat scroll 0 2px transparent;
	padding-left:18px;
	margin:0;
	line-height:1.2em;
	min-height:19px;
	display:inline-block;
}
```

I think changing to **background:url(../images/outofstock.png) no-repeat scroll 0 2px transparent;** would fix the issue

**Comment by misulicus** [comment]
Fixed in Gold Cart
