### ISSUE TITLE
Select2 display issue on presentation category filters

### ISSUE THREAD

**Issue by curtismchale** [wp-e-commerce/WP-e-Commerce#1880]
Seems like the Select2 fields don't display correctly on the Presentation settings in FF.

![screen shot 2015-05-20 at 8 21 36 am](https://cloud.githubusercontent.com/assets/74561/7729402/6e9019ac-fec9-11e4-83a6-c58d5ce223b3.png)

**Comment by JustinSainton** [comment]
Fixed.
