### ISSUE TITLE
FedEx shipping module

### ISSUE THREAD

**Issue by TMUND** [wp-e-commerce/WP-e-Commerce#1885]
Hello wp-e-commerce, 

I recently purchased the FedEx plugin for my website and am having an issue finding the "print label" button in my WP dashboard. 

When I used to have UPS, if I went to; Dashboard -> Store Sales -> and then clicked on a sold item; at the bottom of the page under "Actions" there used to be a "print shipping label" button which would allow me to print the shipping label directly from the dashboard and not have to go back to UPS to get that. 

Is this supported in the FedEx plugin? I can't seem to find the information/button anywhere...

Thanks!

**Comment by TMUND** [comment]
@JustinSainton Still looking for an answer to this if anyone knows...?

**Comment by JustinSainton** [comment]
I don't believe this is supported in the FedEx plugin.  If I recall correctly, it _may_ be supported for FedEx via the stamps.com plugin that @JeffPyeBrook built.  I'll let him weigh on on that, but it may be a good solution for you.

**Comment by TMUND** [comment]
@JustinSainton thanks!

**Comment by JeffPyeBrook** [comment]
Yes, the stamps.com plugin will provide quotes and label printing that includes paid postage.

**Comment by TMUND** [comment]
@JeffPyeBrook Stamps.com plugin will provide label printing for USPS only or also for FedEx? I am trying to use FedEx exclusively for shipping.

**Comment by JeffPyeBrook** [comment]
USPS only
