### ISSUE TITLE
'Sort Product By' order defaulting to 'Descending'

### ISSUE THREAD

**Issue by ablears** [wp-e-commerce/WP-e-Commerce#1889]
On WP e-Commerce 3.9.3 and gold cart 2.9.7.7, under Settings -> Store I have 'Sort Product By:' set to 'Drag and Drop' + 'Ascending'.

I go into Products and set the order I want. On the front end the products are in the correct order. 

All goes well for a few days, then I find the 'Sort Product By:' order has switched to 'Descending'. I haven't been able to identify what action is causing this switch unfortunately. I have a report from a client saying it happened during a time they hadn't been logged in but that's all.

I realise this is all a bit vague, let me know any questions.

cheers
Anthony

.

**Comment by kehall** [comment]
I don't believe this is actually changing to Descending, it's basically like it swaps around each time - there must be a sort order reversal in wordpress that is actually reversing the dragged and dropped sort order... It appears to have been around for at least 2 months or whenever (I think WP 4.x) was shipped.

You can check this by drag/drop an item to the bottom of the list... next time you go in, it'll be at the top with the previously next-to-bottom item underneath it (and the rest of your sorted list as you'd expect). It's almost impossible to achieve a correct sort order in this state!

All I can do is say what I think's happening, I have no idea how to fix though, sorry.

**Comment by misulicus** [comment]
Not sure if you guys still see this but i just tested and they seem to "stick" to the order i`m setting them to. Using latest master from github

**Comment by JustinSainton** [comment]
Going to close this as unconfirmed until we can reliably identify the root issue here at play. If any further information can be gathered, please feel free to re-open.
