### ISSUE TITLE
No error thrown if failed to insert purchase log

### ISSUE THREAD

**Issue by DustinWoods** [wp-e-commerce/WP-e-Commerce#1892]
If a MySQL error occurs inserting a purchase log row, wpec still continues to submit transaction to gateway, and also proceeds to take user to transactions results page.

In wpsc_submit_checkout within ajax.php, after the purchase log is created, there needs to be check to ensure the MySQL query was successful before processing the transaction. The end user should receive an error when this occurs, alerting them to try again.

I will be submitting a pull request soon.

**Comment by DustinWoods** [comment]
To clarify, this is an issue with theme-engine-v1: /wpsc-components/theme-engine-v1/helpers/ajax.php

**Comment by instinct** [comment]
We need to put theme engine v1 to rest and fast!

**Comment by JustinSainton** [comment]
It's quite likely that this issue also exists in TEV2

**Comment by DustinWoods** [comment]
TEV2 creates a purchase log record in save_shipping_and_billing_info. Since it creates the purchase log in a separate request from the final transaction step, it may not cause the same issue as in TEV1.

**Comment by JustinSainton** [comment]
Hi @DustinWoods,

Let me know if you're able to submit a PR for this, would love to see it merged.  Thanks!

**Comment by DustinWoods** [comment]
Thanks for reminding me!

**Comment by JustinSainton** [comment]
No problem, thanks for the PR!
