### ISSUE TITLE
When editing a variation it allows you to select another variation as the parent

### ISSUE THREAD

**Issue by benhuson** [wp-e-commerce/WP-e-Commerce#1893]
When creating a new variation in the admin, the drop down menu only lets you choose a Variation Set to which to assign it (i.e. a variation term with parent = 0).

However, when you click in to edit a variation that is already created it lets you change the parent to another variation (where term parent > 0) rather than just a variation set which is unexpected behaviour and could cause problems.

This drop down menu should only list variation sets.
See attached images which show the drop down menu listing everything.

![edit-var](https://cloud.githubusercontent.com/assets/765285/7857179/745a5b0a-0526-11e5-8e09-196d1d15cdf0.png)

![edit-var-menu](https://cloud.githubusercontent.com/assets/765285/7857183/78076216-0526-11e5-8cef-8cc957370b53.png)

**Comment by benhuson** [comment]
Loosely related to #257

**Comment by JustinSainton** [comment]
@benhuson Something like this?

```php
add_filter( 'taxonomy_parent_dropdown_args', function( $args, $taxonomy, $context ) {

	if ( 'wpsc-variation' == $taxonomy && 'edit' == $context ) {
		$args['depth'] = 1;
	}

	return $args;
}, 10, 3 );
```

**Comment by benhuson** [comment]
Yep, that's what I was thinking.
Was thinking about how to just target that admin page and had forgotten there was a `$context` parameter ;)

**Comment by JustinSainton** [comment]
@benhuson Sweet!  Happy to merge a PR, otherwise, I'll get to it as soon as I can :+1:
