### ISSUE TITLE
Corrupt table exposes user data

### ISSUE THREAD

**Issue by spuntotheratboy** [wp-e-commerce/WP-e-Commerce#1901]
This issue began for me after upgrading to WPEC 3.9.3 on WP 4.2.2

On the checkout page, customers were presented with the previous customer's personal information.

On investigation, it turned out that every customer was being identified as a bot. The function `_wpsc_create_customer_id()` would return WPSC_BOT_VISITOR_ID because `wpsc_create_visitor()` would return false, this in turn because its attempt to insert into the table `wp_wpsc_visitors` was failing due to corruption of the table.

Running `REPAIR TABLE wp_wpsc_visitors` fixed the problem.

I suggest this urgently needs to be addressed in two ways:

First, it seems that a number of other people have begun to experience this issue since upgrading to 3.9.3 - that may very well be a coincidence, but if there's any chance that the upgrade process contributed to the corruption of the table then someone needs to investigate that.

Secondly, that sort of error should not lead to sensitive data being exposed publicly. The current situation is that if the attempt to determine a visitor's visitor ID, or to create a new one, fails at any point, the fallback is to assign them the visitor ID 1 (which coincidentally identifies them as a bot). If they fill in the checkout form, their data is saved against that ID, and reloaded when the next customer, also with the ID 1, comes to the checkout. Perhaps a good solution would be not to load customer data into the checkout form if their visitor ID is 1, i.e. unless they have been uniquely identified.

**Comment by JustinSainton** [comment]
Thanks for the report, @spuntotheratboy.  That's _super_ helpful for us.  We'll be shipping a 3.9.4 release to rectify this issue.  My proposed plan of attack is as follows, I'd love your thoughts on it:

1. On admin_init, for administrators, check if the visitor meta table is in need of repair.  If it is, link to repair page.
1. In `wpsc_(add|delete|update|get)_visitor_meta`, check if `$visitor_id == WPSC_BOT_VISITOR_ID `.  If true, return early.

I think that would sufficiently address the issue.  Would welcome your thoughts, as well as @JeffPyeBrook's thoughts on this.

Thanks again!

**Comment by JustinSainton** [comment]
This is now fixed in master, shipping a 3.9.4 release with the fix.

**Comment by JustinSainton** [comment]
If you're able to test our 3.9.4 branch, that'd be awesome - https://github.com/wp-e-commerce/WP-e-Commerce/tree/branch-3.9.4

**Comment by spuntotheratboy** [comment]
You're welcome - it was kinda fun, after it was just horribly frustrating!

I really don't think I know enough about the internals of the plug-in to have a valid opinion on your method, but it sounds good, as far as I can tell.

Also I'm off work until next week so I won't be able to test the new branch until then. I'll certainly do so when I get back.

Thanks,
Ben
