### ISSUE TITLE
Typo in wpsc_user_log_functions

### ISSUE THREAD

**Issue by ozoneboy** [wp-e-commerce/WP-e-Commerce#1904]
Looks like a typo on line 129 of wpsc-theme/functions/wpsc-user_log_functions.php where "wpsc_checout" should be "wpsc_checkout"?

**Comment by JustinSainton** [comment]
Good catch!  Though, for what it's worth, the templates/files in the /wpsc-theme folder have not been used for several releases - they are deprecated, in favor of /wpsc-components/theme-engine-v1.

Thanks!
