### ISSUE TITLE
Purchase button broken after last update

### ISSUE THREAD

**Issue by TMUND** [wp-e-commerce/WP-e-Commerce#1907]
Hi WP eCommerce team, 

I updated my eCommerce plugin last week since I saw a new one had come out and now my "purchase" button is broken. The button seems to capture the sale as I can see it in my sales log in the dashboard, however it does not take me to the "transaction complete" screen and all of the payments have been coming back as "payment declined" 

Any idea where I should start looking for a solution? 

Thanks!

**Comment by TMUND** [comment]
eCommerce Version 3.9.4 and wp_version = '4.2.2' if that helps

**Comment by TMUND** [comment]
Also, please let me know if there is a better place to post issues such as this Justin :)

**Comment by TMUND** [comment]
After some looking around I found #1038, which seems to be what is happening to me. Unfortunately, I am still not sure what the fix would be to ensure the customer gets taken to the "transaction results" page...

**Comment by JustinSainton** [comment]
Hi @TMUND,

Can you confirm what gateway you're using?

**Comment by TMUND** [comment]
Authorize.net AIM

**Comment by JustinSainton** [comment]
I imagine you're using it from Gold Cart?  Do you know what version of Gold Cart you're using?

**Comment by TMUND** [comment]
Yup, Version 2.9.7

**Comment by JustinSainton** [comment]
Ah, you need to upgrade to 2.9.9.  Authorize.net updated their certificates and APIs in a pretty breaking way - if you don't have the updated certificates that we ship with 2.9.9, all payments are declined.  Lame sauce.

**Comment by TMUND** [comment]
AHA! Thanks @JustinSainton, I figured something updated and broke but couldn't track it down. I don't see the update available through WP dashboard, where else can I find it?

**Comment by JustinSainton** [comment]
You'll need to download it in your account at wpecommerce.org
