### ISSUE TITLE
wpsc_merchant::set_authcode() doesn't update object cache

### ISSUE THREAD

**Issue by webaware** [wp-e-commerce/WP-e-Commerce#1916]
The method [`wpsc_merchant::set_authcode()`](https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-includes/merchant.class.php#L326-L346) does a direct update of the purchase log table, without updating the object cache. On sites with a persistent object cache, this leads to loss of the transaction's auth_code when the transaction is subsequently updated, e.g. status changed from `Accepted Payment` to `Closed Order`.

I'm changing my gateway code to use `wpsc_update_purchase_log_details()` instead, since it properly handles cached data and I can't be sure that all sites with my gateway will have updated WP eCommerce. However, I recommend this problem be fixed because I imagine that other gateways are similarly calling the `set_authcode()` method and expecting the data to persist.

**Comment by JustinSainton** [comment]
Hi @webaware,

Thanks for the report!  We'll get this fixed ASAP.
