### ISSUE TITLE
Cached meta needs invalidating when changed.

### ISSUE THREAD

**Issue by benhuson** [wp-e-commerce/WP-e-Commerce#1918]
Just need to re-check the implications of #1389 and #1894

Need to check that when category and country/region meta is changed we invalid the cache.

Hopefully these will be using some sort of wpsc_update_meta function/API where we can add in functionality to delete meta cache.

If not, we need to add one.

**Comment by JustinSainton** [comment]
@misulicus reported, and I confirmed, that after #1914 was merged, we get a PHP warning on the Products page in the admin (List Table view of products)

https://cloudup.com/crk7wsCKiea

If you var_dump() the $terms in wpsc_get_terms_category_sort_filter(), it'll show up in the quick-edit view and actually seems to have two arrays rather than a single array.  The first, an array of Term IDs - the second, the expected array.

Very odd.

**Comment by benhuson** [comment]
The issue is that when using get_terms() you can specify a fields argument to just return certain term fields. The default is to return term objects but if you specify anything other than 'all' then an array of values will be returned instead.

I was assuming $terms were always term objects when going through that filter but that's not the case.

@JustinSainton Your commit fixes the issue but actually bypasses the caching functionality which helps reduce the amount of DB requests.

The `wpsc_update_meta_cache( 'wpsc_category', $term_ids )` needs to happen before looping through the terms as this updates the meta cache (pre-fetches the meta in bulk and caches it) meaning that the subsequent calls to `wpsc_get_meta()` in the loop do not hit the database.

In my PR above I check that the fields arg is either not set or is set to 'all' before doing anything.

In my testing displaying 10 products on the product admin screen with 24 categories, the above code saves 20 DB queries.

**Comment by JustinSainton** [comment]
@benhuson :+1: Looks great.  Cheers!

**Comment by benhuson** [comment]
Can also confirm cache already seems to be deleted when updating and deleting meta.

See in wpsc_update_meta():
https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-includes/meta.functions.php#L80

See in wpsc_delete_meta():
https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-includes/meta.functions.php#L118

:smile:

**Comment by JustinSainton** [comment]
This is why we love you, @benhuson

**Comment by benhuson** [comment]
Right back at ya
