### ISSUE TITLE
The '_wpsc_product_gallery' meta is copied as-is when duplicating a product.

### ISSUE THREAD

**Issue by benhuson** [wp-e-commerce/WP-e-Commerce#1932]
The `_wpsc_product_gallery ` meta value should be updated to references new image IDs when a product is duplicated.

Follows on from other product/image duplication enhancements in #1672

**Comment by JustinSainton** [comment]
@benhuson Is this something you think we can land before beta2? That will likely be dropping next Wednesday..

If not, that's totally fine, but we'll punt it to 4.1 at that time.

**Comment by benhuson** [comment]
I'll see what I can do ... but no promises

The first step would be to ensure _wpsc_product_gallery meta isn't copied across if images are set to not copy. I can probably get that done but may not have time to fit in the remapping of image IDs if images are copied.

**Comment by benhuson** [comment]
That should do it - including remapping of image IDs in gallery meta :wink:
