### ISSUE TITLE
Authorize.net is changing URLS . Update needed for Gold Cart

### ISSUE THREAD

**Issue by Bloke1** [wp-e-commerce/WP-e-Commerce#1952]
I have been informed Authorize.Net is making changes to their processing URLS. Now through June 2016) — they are creating three new URLs for transaction processing that are hosted by Akamai. This will need to be updated for Gold Cart. http://www.authorize.net/support/akamaifaqs/?utm_campaign=Akamai%20Initial%20Email%20to%20Merchants.html&utm_medium=email&utm_source=Eloqua

**Comment by JustinSainton** [comment]
@Bloke1 Great minds - https://github.com/wp-e-commerce/Gold-Cart/issues/8
