### ISSUE TITLE
Theme Engine v2 globally sets posts_per_archive_page to -1

### ISSUE THREAD

**Issue by borkweb** [wp-e-commerce/WP-e-Commerce#1954]
The `theme-engine-v2/helpers/template-engine.php` file [hooks to](https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-components/theme-engine-v2/helpers/template-engine.php#L204) `pre_get_posts` and if the query _isn't_ a WP-e-Commerce one then `posts_per_archive_page` gets set to `-1`. Any `posts_per_archive_page` setting set external to WP-e-Commerce gets overridden here (which isn't desirable, of course :) )

__WP version:__ Any
__WP-e-Commerce version:__ 4.0 Beta 1

**Comment by JustinSainton** [comment]
Thanks for the detailed report, @borkweb.  Really appreciate it!

I suppose a good solution here would simply be to remove the following code:

```php
else {
		$query->set( 'posts_per_archive_page', -1 );
	}
```

Is that what you were thinking?

**Comment by borkweb** [comment]
Yeah, that'd probably work swimmingly!

**Comment by JustinSainton** [comment]
Great, fixed!  Thanks again for the report!

**Comment by borkweb** [comment]
You rock!

**Comment by JustinSainton** [comment]
staaaaahp
![image](https://cloud.githubusercontent.com/assets/1168754/8987134/613eaeb4-3694-11e5-9d04-4df65b47f790.png)
