### ISSUE TITLE
Pre Populate Checkout Form From Account Details If Logged In

### ISSUE THREAD

**Issue by edoriv** [wp-e-commerce/WP-e-Commerce#1967]
Regardless of previous purchases the checkout form should be populated with the customers details from their account if they already have an account and are logged in.

Maybe this should possibly be something that can be toggled on or off optionally by the store owner.

**Comment by JustinSainton** [comment]
@edoriv can you confirm this is an actual issue?  Seems to work fine for me in TEv1 and TEv2.  If a user is logged in and already has checkout_details user meta, it loads their information.
