### ISSUE TITLE
Remove Checkout Shipping Form Section If Cart Does Not Contain Shippable Items

### ISSUE THREAD

**Issue by edoriv** [wp-e-commerce/WP-e-Commerce#1968]
If the cart doesn't contain a shippable item the shipping section of the checkout form should not be shown or validated.

This has been asked on a few occasions and I do feel it would cut down on friction where a cart doesn't contain shippable items.

**Comment by JustinSainton** [comment]
Not going to implement in core for now. I blogged about the rationale and a work-around.  

This ticket would be the proper place for any one else to weigh in on better rationale in favor of the suggestions herein.

http://zao.is/2015/08/wp-ecommerce-how-to-conditionally-remove-shipping-fields-from-the-checkout-form/
