### ISSUE TITLE
WordPress 4.3 List table notices

### ISSUE THREAD

**Issue by misulicus** [wp-e-commerce/WP-e-Commerce#1976]
Got them on the Checkout settings page for now.

`Notice: Undefined offset: 3 in D:\wamp\www\wpecomm-dev\wp-admin\includes\class-wp-list-table.php on line 993`

Debug Backtrace seems to show here:

```
9	0.4660	25870776	WPSC_Settings_Tab_Checkout->display( )	...\settings-page.php:483
10	0.4680	25874976	print_column_headers( )	...\checkout.php:424
11	0.4680	25877024	WP_List_Table->print_column_headers( )	...\list-table.php:80
```

**Comment by JustinSainton** [comment]
Fixed in core: https://core.trac.wordpress.org/ticket/34148
