### ISSUE TITLE
TE v2 - Product image links to product URL

### ISSUE THREAD

**Issue by misulicus** [wp-e-commerce/WP-e-Commerce#1979]
Maybe it should show the zoomed product image ?

**Comment by JustinSainton** [comment]
Personally, I'd like to avoid a situation where we're including lightbox scripts in core again.  Because then we get into the Thickbox/Colorbox, etc. situation.  I'd _rather_ the images do nothing, and make it easy for lightbox plugins or zooming plugins to hook in, add a class, or do whatever they need to do to integrate with the images.

**Comment by instinct** [comment]
Agreed. However I feel like we should make sure there is a plugin readily available for our users since it was a core feature that historically was well used. Do you think any of the light of plugins out there will just work out of the box with TE v2?

What does WordPress do these days?

**Comment by JustinSainton** [comment]
WP doesn't do anything on the front-end for lightboxes.  Jetpack would be the closest thing to core, and they have their tiled carousels.  We could provide some compat with that, I suppose?

**Comment by benhuson** [comment]
@JustinSainton Could we perhaps have some sort of 'product_image_link' filter which could be used to link an image to a large image file or page, but have it default to returning an empty string - i.e. no link?

That way you could add support for Lightbox / Fancybox / whatever via plugin as many seem to use the href value as the source for a popup.

Or I'm pretty sure that Jetpack carousels just filter the gallery shortcode output so is it a case we need to output galleries using the gallery shortcode somehow:

```
do_shortcode( '[gallery link="file" ids="5090,5089,5088"]' );
```

**Comment by JustinSainton** [comment]
Resolved as of https://github.com/wp-e-commerce/WP-e-Commerce/commit/9ff2d845572882c5c362254bf6d5231d12fb1eef
