### ISSUE TITLE
Fancy "Added to Cart" notification not displaying in 3.10.0

### ISSUE THREAD

**Issue by jbeales** [wp-e-commerce/WP-e-Commerce#1990]
The function `_wpsc_theme_engine_v1_has_actions()` removes the function `wpsc_fancy_notifications()` from the `wpsc_theme_footer` action. In 3.9.5 `wpsc_fancy_notifications()` wasn't added to `wpsc_theme_footer` until after `_wpsc_theme_engine_v1_has_actions()` was called, but in 3.10.0 `_wpsc_theme_engine_v1_has_actions()` is called twice more, so `wpsc_theme_footer` is stripped of its actions.

`_wpsc_theme_engine_v1_has_actions()` is only called by `_wpsc_maybe_activate_theme_engine_v2()`, but it is called several times.

**Comment by jbeales** [comment]
I'm not an expert on the new theme engine, but why does `_wpsc_theme_engine_v1_has_actions()` remove the actions that core uses, not just exempt them from the true/false return of `_wpsc_theme_engine_v1_has_actions()`?

**Comment by danmilward** [comment]
I wasnt aware that 3.10.0 used the new Theme engine... could you add a pull request adding Fancy Notifications back to the new Theme engine OR would you consider spinning that into a Plugin with us - possibly in collaboration with @benhuson ?

Before we go live with 4.0 we'll have a fancy notification solution. If its not in the core plugin there will be a message alerting the user where to find the missing functionality.

**Comment by benhuson** [comment]
@danmilward I've started playing with splitting out Fancy Notifications as a component so that it could then be split off as a plugin and made compatible with the new Theme engine. Will update in issue #516 once I have made some progress.

**Comment by danmilward** [comment]
Thanks Ben!! I need to think about UI for that too - there needs to be something that tells the user where to find lost functionality :)

d

**Comment by benhuson** [comment]
If we detect that a user had some functionality active then it should probably shown a prominent message at the top of the admin screen.
