### ISSUE TITLE
Ensure we don't encounter fatal errors w/ wpsc_get_checkout_url()

### ISSUE THREAD

**Issue by JustinSainton** [wp-e-commerce/WP-e-Commerce#1992]
From @barryhughes, our friend over at Modern Tribe:

The fatal is that wpsc_get_checkout_url() is undefined, but is called from WPSC_Payment_Gateway::get_shopping_cart_payment_url(). 

I do now see that method has a check in place to avoid this, however in my case the wpsc_get_active_theme_engine option is set to "2.0" (perhaps from previous testing with your beta or something like that - and I may not have cleaned up as thoroughly as I should have...

**Comment by misulicus** [comment]
Should be fixed via https://github.com/wp-e-commerce/WP-e-Commerce/commit/4fdc7cd8e2fd03744d571d536017a0fbaf033532

**Comment by jtsternberg** [comment]
That would only be fixed by [4fdc7cd](https://github.com/wp-e-commerce/WP-e-Commerce/commit/4fdc7cd8e2fd03744d571d536017a0fbaf033532) it it's associated with switching theme engines. Is there a way to know that?

**Comment by JustinSainton** [comment]
Having switched between theme engines constantly for the last week, I have yet to re-experience this error.  Marking as closed until someone runs into it again.
