### ISSUE TITLE
Payment Gateways init used data that may not be loaded until later

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#1995]
In file payment-gateway.php 

replace
**WPSC_Payment_Gateways::init();**

with
**add_action( 'wpsc_loaded', array( 'WPSC_Payment_Gateways', 'init' ) );**

**Comment by JustinSainton** [comment]
@JeffPyeBrook What specifically is it attempting to access that might not be loaded?

**Comment by JeffPyeBrook** [comment]
I recall that the specific fatal came from one of the paypal gateways looking for a piece of country data and/or customer meta. 

But the issue is really that any payment gateway should be able to rely on WPeC being up and running and the core data structures initialized. If the gateways are loaded off if the "php include" then that will never be the case.

**Comment by JustinSainton** [comment]
Closed in 341aea75a4b5b2f96f1301a675184cc5fe0027a3
