### ISSUE TITLE
Sales Dashboard Widgets May Not Calculate Correctly

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#1996]
Dashboard widgets are hardcoded to use status values rather than "complete" transaction status. If filters are used to add or adjust available status values widgets will not have correct values.

**Comment by JeffPyeBrook** [comment]
@JustinSainton yes

**Comment by JustinSainton** [comment]
Fixed in https://github.com/wp-e-commerce/WP-e-Commerce/pull/1998/commits/223521f304d43646afdab9d74c136cb7a238a1ef
