### ISSUE TITLE
Can't checkout

### ISSUE THREAD

**Issue by jorrit** [wp-e-commerce/WP-e-Commerce#2010]
I am experiencing a problem that seems to be bothering more people:

https://wordpress.org/support/topic/customers-cant-check-out
https://wordpress.org/support/topic/cant-checkout-when-shipping-is-activated
https://wordpress.org/support/topic/checkout-page-keeps-reloading-instead-of-sending-to-paypal-for-payment

I've narrowed the problem down to `_wpsc_vistor_shipping_same_as_billing_meta_update()`. The following code copies empty `shipping` values to `billing` fields. I can't imagine why:

```php
			} elseif ( $meta_key_starts_with_shipping ) {
				$checkout_names = wpsc_checkout_unique_names();

				$other_meta_key_name = 'billing' . substr( $meta_key, strlen( 'shipping' ) );

				if ( in_array( $other_meta_key_name, $checkout_names ) ) {
					wpsc_update_visitor_meta( $visitor_id, $other_meta_key_name, $meta_value );
				}
			}
```

**Comment by misulicus** [comment]
Go in your theme directory and check if you have the theme file wpsc-shopping_cart.php.
If you do rename that to something else and flush the cache from Presentation page.
Give it another try.

Also make sure you have the billing Country/State fields enabled on the checkout page.

**Comment by jorrit** [comment]
Thanks for your fast reply, I really appreciate that. The cause was that I had replaced `$shipping_same_as_billing = wpsc_get_customer_meta( 'shipping_same_as_billing' );` with `$shipping_same_as_billing = true` to have the checkbox enabled from the start. Somehow this lead to the shipping values overwriting the billing values. I still do not understand the code I quoted above, though.

**Comment by misulicus** [comment]
In recent updates the SHipping same as billing function has been changed to work using customer meta. I`m not sure exactly when.
But usually most of the causes of checkout "refreshing" is old WP eCommerce theme files like the checkout one

**Comment by JeffPyeBrook** [comment]
There is a filter *$meta_value = apply_filters( 'wpsc_get_customer_meta', null, $key, $id );*, you can use to override a stored value.

**Comment by jorrit** [comment]
Thanks for your replies.
