### ISSUE TITLE
Domain Problem

### ISSUE THREAD

**Issue by kobinatorke** [wp-e-commerce/WP-e-Commerce#2025]
So, I have a domain (graphicmc.net) and I wanted to delete my domain in github to host it on another server host but when I open the site (the site is deleted out of github) it says the 404 page from github.

Please help me,

Kobe

**Comment by kobinatorke** [comment]
Please help me..

Kobe

**Comment by JustinSainton** [comment]
Hi @kobinatorke,

I'm not sure i understand your problem, or how it is related to WP eCommerce?

**Comment by kobinatorke** [comment]
I don't know mutch about this but I have a domain called graphicmc.net, I had it in a repository and I deleted it because i wanted to host the website on a other website, so everything that linked the domain with github is deleted (I think) and normally everything is set up correctly (with the new web hosting) but when I go to the domain (graphicmc.net) it goes to a 404 website from github.

Sorry for bad English :D 

Kobe

**Comment by JustinSainton** [comment]
Hi @kobinatorke,

It sounds like you may need to connect with Github to see if they have a way to restore deleted repositories.  You can do that at this link:

https://github.com/contact

I'm still unclear on what this has to do with WP eCommerce, as such, I'm going to go ahead and close this issue.
