### ISSUE TITLE
Broken CSS on http://wpecommerce.org/

### ISSUE THREAD

**Issue by TMUND** [wp-e-commerce/WP-e-Commerce#2027]
Attached screenshot. Occurs on Mac Firefox and Chrome. 

![screen shot 2015-11-14 at 10 46 56 am](https://cloud.githubusercontent.com/assets/10443437/11165188/12d0a340-8abd-11e5-860f-542138c143ac.png)

**Comment by JustinSainton** [comment]
Thanks for the heads up, we'll get that fixed.
