### ISSUE TITLE
Javascript errors in admin Collapse menu

### ISSUE THREAD

**Issue by misulicus** [wp-e-commerce/WP-e-Commerce#2028]
I'm getting Uncaught TypeError: jQuery.plot is not a function

**Comment by JustinSainton** [comment]
What plugins are active? We don't have any graphing library in core (yet, #462)

**Comment by JustinSainton** [comment]
This is not fixed: https://wordpress.org/support/topic/bug-affecting-admin-menu-collapse?replies=7
