### ISSUE TITLE
WP crash with WP-ecommerce 3.10.1

### ISSUE THREAD

**Issue by gdeuchst** [wp-e-commerce/WP-e-Commerce#2030]
I have installed wp-ecommerce 3.10.1 on wordpress 3.9.1 (cannot update for now), but when I activate it, WP completely crash, like HTML was no more interpreted...
Is it a version issue ? Can I download an older, compatible one ?

**Comment by misulicus** [comment]
Try enabling debug in wp-config.php and there should  be an error message on the screen.

**Comment by JustinSainton** [comment]
You should also note, the minimum WP version for WPeC 3.10. is WordPress 4.1

https://github.com/wp-e-commerce/WP-e-Commerce/blob/branch-3.10.1/readme.txt#L5

The most recent version that supports WordPress 3.9 is WP eCommerce 3.9.3.

https://downloads.wordpress.org/plugin/wp-e-commerce.3.9.3.zip

**Comment by gdeuchst** [comment]
It works, thank you :)
