### ISSUE TITLE
Merchant Payment Gateway V3 backwards compatability

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#2052]
Method register_file needs to lower case internal name to stay compatible with TE1 and older theme files to maintain compatibility.

**Comment by JustinSainton** [comment]
@JeffPyeBrook Can you confirm this is fixed as of https://github.com/wp-e-commerce/WP-e-Commerce/commit/c9b03c6fdbfa4b802b4a73770798d22a1780a084 ?
