### ISSUE TITLE
"Featured Image" metabox conflict

### ISSUE THREAD

**Issue by APEWAW** [wp-e-commerce/WP-e-Commerce#2058]
Hello, 

"Featured Image" metabox has disappeared since the last WordPress update. When I disable the plugin, its works. Do you have any solution? 

Thank you,

**Comment by APEWAW** [comment]
Hello, 

Any idea to solve this problem?

Thank you,

**Comment by misulicus** [comment]
Could be a conflict with another plugin perhaps. have you tried disabling all other plugins first to rule that out ?
