### ISSUE TITLE
404 on malformed CSS query?

### ISSUE THREAD

**Issue by luxpir** [wp-e-commerce/WP-e-Commerce#2068]
I think it relates to: `WP-e-Commerce/wpsc-components/theme-engine-v1/helpers/page.php`
And the `wpsc_get_template_file_url` function

As it calls this line:
`<link rel='stylesheet' id='wpsc-theme-css-css'  href='http://www.domain.com/wp-content/plugins/wp-e-commerce/wpsc-components/theme-engine-v1/templates/wpsc-marketplace.css?ver=3.11.2.ffbc44e' type='text/css' media='all' />`

Which 404's and affects the site load time. My page.php differs from the github version - the site is using 3.11.2.

Thanks for your assistance.

**Comment by misulicus** [comment]
Is there an error somewhere ? Could you post a screenshot with the page you are on and the error you see.

**Comment by luxpir** [comment]
The error's in Chrome dev tools - this one stray CSS request was slowing down the overall page load and then 404'ing. Because it wasn't there, of course. I added it, anyway, and just put `/** Filler **/` text in it, but strange it was happening.

I *think* it came from here (`wp-e-commerce/wpsc-components/theme-engine-v1/helpers/page.php`):

`wp_enqueue_style( 'wpsc-theme-css',               wpsc_get_template_file_url( 'wpsc-' . get_option( 'wpsc_selected_theme' ) . '.css' ), false, $version_identifier, 'all' );
                wp_enqueue_style( 'wpsc-theme-css-compatibility', wpsc_get_template_file_url( 'compatibility.css' ),                                    array( 'wpsc-theme-css' ), $version_identifier, 'all' );

                if ( function_exists( 'wp_add_inline_style' ) )
                        wp_add_inline_style( 'wpsc-theme-css', wpsc_get_user_dynamic_css() );
                else
                        wp_enqueue_style( 'wp-e-commerce-dynamic', wpsc_get_dynamic_user_css_url(), array( 'wpsc-theme-css' ), $version_identifier );

                if( get_option( 'product_ratings' ) == 1 )
                        wp_enqueue_style( 'wpsc-product-rater',           WPSC_CORE_JS_URL      . '/product_rater.css',                                       false, $version_identifier, 'all' );

        }`

**Comment by misulicus** [comment]
What pare are you on when that is showing up ?

**Comment by luxpir** [comment]
Any and all! Even the homepage, which confused me, but then I thought maybe wpsc was inserting headers/code into the WP templates...?

**Comment by misulicus** [comment]
Can you send me an email at mihai@wpecommerce.org with wp-admin and FTP info so i can take a look ?
I just checked and i don't see the issue anywhere on my dev site.

**Comment by luxpir** [comment]
Done. Not including wp-admin/FTP info for now.

**Comment by luxpir** [comment]
Quick follow-up for any future readers: we concluded it must be my theme (Optimize by WooThemes) causing the issue, despite the name of the CSS file produced (`wpsc-marketplace.css`), we can't figure out where in the code it would be produced. My only other thought was that it could be an old version of the plugin with some legacy logic causing an issue, despite the fact that grepping the dir finds nothing.
