### ISSUE TITLE
Fatal error on multiple cart items

### ISSUE THREAD

**Issue by misulicus** [wp-e-commerce/WP-e-Commerce#2071]
````
[12-Mar-2016 19:29:36 UTC] PHP Warning:  Attempt to modify property of non-object in public_html/wp-content/plugins/wp-e-commerce/wpsc-includes/wpsc-meta-visitor.php on line 618
[12-Mar-2016 19:29:36 UTC] PHP Fatal error:  Call to a member function calculate_shipping() on a non-object in public_html/wp-content/plugins/wp-e-commerce/wpsc-includes/cart.class.php on line 1066
````

As per the report it seems to happen when adding multiple items to the cart with a coupon code and perhaps when removing an item from cart ?
Still not sure what triggers the issue.

**Comment by misulicus** [comment]
Could not replicate on master and fresh wpec setup

**Comment by JustinSainton** [comment]
Closing pending further feedback.

**Comment by kid5parkle** [comment]
Hey Justin.  I'm having trouble with wp e-commerce Version 3.13.1

I was using my shopping cart to test out a coupon code and had multiple items in cart. I then deleted one and instantly had the usual blank white page come up with this:

Warning: Attempt to modify property of non-object in /home4/dancecon/public_html/wp-content/plugins/wp-e-commerce/wpsc-includes/wpsc-meta-visitor.php on line 618

Fatal error: Call to a member function calculate_shipping() on double in /home4/dancecon/public_html/wp-content/plugins/wp-e-commerce/wpsc-includes/cart.class.php on line 1117

——————————–

Now, my website is unusuable when I activate the wp e-commerce plugin. It stays on this screen :/

**Comment by kid5parkle** [comment]
christ almighty this worked: 

Righto, how i fixed this for the time being, i removed all lines in the tables wp_wpsc_visitors, wp_wpsc_visitor_meta that were references to the user account I was having issues with. I’ll post again if the error returns.

I dont allow users on our site except the admin so I deleted ALL visitors from the day this problem started...
