### ISSUE TITLE
Bug report: category images no longer working

### ISSUE THREAD

**Issue by charlotteki** [wp-e-commerce/WP-e-Commerce#2079]
Hi, the category images are no longer uploading properly - no problems with the product images uploading. I turned off all other plugins and reverted to default themes still doesn't work - running:

WordPress 4.5.1
Version 3.11.2 | By WP eCommerce

Interestingly I have another almost identical site running 
wordpress 4.5 and Version 3.11.2 and it works still

Just wanted to let you know there's a problem.

**Comment by misulicus** [comment]
I just tested that and it uploaded fine. Is there a way to replicate? Could you please perhaps make some screenshots of the issue ?

**Comment by charlotteki** [comment]
ummm, weird so I wonder what is causing them not to "stick" they used to work until very recently...

**Comment by misulicus** [comment]
Can you mail me at mihai@wpecommerce.org with admin logins so i can give it a test ?

**Comment by misulicus** [comment]
@charlotteki the above fix is working and resolves the issue

**Comment by charlotteki** [comment]
Thank you. I just tested it and it didn't make any difference to my installation. :-( 
I do appreciate that you investigated it.

**Comment by charlotteki** [comment]
Yes fixed thank you.
