### ISSUE TITLE
Adding a weekly cron schedule by default in core ?

### ISSUE THREAD

**Issue by misulicus** [wp-e-commerce/WP-e-Commerce#2083]
Was thinking in perhaps adding a weekly cron event in core
inside wpsc-functions right after wpsc_cron()
````
/**
 * wpsc_add_weekly_schedule()
 *
 * Creates a weekly schedule event
 *
 * @param none
 * @return void
 */
function wpsc_add_weekly_schedule( $schedules = array()) {
	$schedules['weekly'] = array(
		'interval' => 604800,
		'display'  => __( 'Once Weekly', 'wp-e-commerce' )
	);
	return $schedules;
}
add_filter( 'cron_schedules', 'wpsc_add_weekly_schedule' );
````

and then change the defaults in wpsc_cron to:
`$default_schedules = array( 'hourly', 'twicedaily', 'daily', 'weekly');`

**Comment by JustinSainton** [comment]
Curious, for what purpose?

**Comment by misulicus** [comment]
Closed via https://github.com/wp-e-commerce/WP-e-Commerce/commit/0ec005fc1e2dcaedde4d2b5ffe229b9d1de9b9fc and https://github.com/wp-e-commerce/WP-e-Commerce/commit/a3fc291adc525c0982972a303802795c1ceff7db
