### ISSUE TITLE
Akamai Change Reminder for Authorize.net by June 30th

### ISSUE THREAD

**Issue by Bloke1** [wp-e-commerce/WP-e-Commerce#2091]
Authorize.Net is now using Akamai to optimize our Internet traffic routing, which includes your transaction requests. Akamai helps safeguard against interruptions caused by issues beyond Authorize.Net’s direct control, such as Internet congestion, fiber cable cuts and other similar issues. 

Using Akamai is currently optional, but will be mandatory for all merchants on June 30th. Upgrade your website or payment solution today to take immediate advantage of Akamai’s benefits. 

The new Akamai transaction URLs that are available now are:

•	Authorize.Net API, XML/JSON format: https://clicktime.cloud.postoffice.net/clicktime.php?X=XID729ueXTJJ6003Xd3&U=https%3A%2F%2Fapi2.authorize.net%2Fxml%2Fv1%2Frequest.api&T=P8NA&HV=X,U,T,S&H=00570aa21cbcea211f765a4bb420d6c46c22a70f&S=Y
•	Authorize.Net API, SOAP format: https://clicktime.cloud.postoffice.net/clicktime.php?X=XID729ueXTJJ6003Xd3&U=https%3A%2F%2Fapi2.authorize.net%2Fsoap%2Fv1%2FService.asmx&T=P8NA&HV=X,U,T,S&H=7a2152830cd3e6b73cfc6f28dc04918a410e643a&S=Y
•	AIM/SIM merchants, name/value pair format: https://clicktime.cloud.postoffice.net/clicktime.php?X=XID729ueXTJJ6003Xd3&U=https%3A%2F%2Fsecure2.authorize.net%2Fgateway%2Ftransact.dll&T=P8NA&HV=X,U,T,S&H=5e92e9f9e9c6f30b1a9729abcebb3d829dc4b86a&S=Y

If you have not already, please review the announcement and the Akamai FAQs to determine what action you should take for your particular solution. If your solution uses a firewall, please pay particular attention to this section of the FAQs to avoid disruptions to your transaction processing.

**Comment by misulicus** [comment]
The changes are already made in the latest Gold Cart version. Closing this since its not a WPeC issue
