### ISSUE TITLE
Product placeholder image does not show when there is no featured image

### ISSUE THREAD

**Issue by lizkaraffa** [wp-e-commerce/WP-e-Commerce#2110]
While the code supports a placeholder image, it doesn't show.

**Comment by JustinSainton** [comment]
Can't replicate this.

**Comment by misulicus** [comment]
@lizkaraffa caqn you let me know how to replicate this

**Comment by lizkaraffa** [comment]
@misulicus If i don't give a product a featured image, when I view items on the main store page, I don't have the placeholder image for them. https://cloudup.com/cT8E3y235Zs

**Comment by lizkaraffa** [comment]
So apparently it was a weird local install bug for me. This is not a universal issue. :joy:
