### ISSUE TITLE
Quick Edit Field Values Not Displaying

### ISSUE THREAD

**Issue by njbebop** [wp-e-commerce/WP-e-Commerce#2141]
Hello,

I updated WP e-Commerce to 3.11.3 today, and I got word that the product quick edit was not auto-populating the fields Stock, Price, Sale Price, SKU, and Weight.  It appears that the code was changed in admin.js to not use jQuery livequery anymore and it looks like something is not working right.  I tried to replace the old code to fill the fields and it worked, however, the rest of the admin had other issues pop up with the following error...

TypeError: jQuery(...).livequery is not a function

Any help will be greatly appreciated, our content people use the Quick Edit since we have a rather large inventory.

Thanks!

**Comment by misulicus** [comment]
This commit will fix the issue
https://github.com/wp-e-commerce/WP-e-Commerce/commit/b137765bd342262b2ade307c7f65829a0bec96c7

It will be available in a .4 release of the plugin
