### ISSUE TITLE
Missing post type on category admin page after saving category

### ISSUE THREAD

**Issue by galbaras** [wp-e-commerce/WP-e-Commerce#2154]
After saving a product category's settings, the URL is only "/wp-admin/edit-tags.php?taxonomy=wpsc_product_category", missing "&post_type=wpsc-product".

This makes the "edit" links on the page , and the links to show each category's products, incorrect, and when clicking the link to show products for a category, WordPress shows an empty list.

I'm thinking that the "save" action may be missing the post_type.

**Comment by misulicus** [comment]
Hey there,
Can you post step by step instructions on how to replicate ?

**Comment by galbaras** [comment]
Go to Products->Categories, click to edit any category, save, look at the URLs.

**Comment by mihaijoldis** [comment]
Unable to replicate on 4.0 branch
@galbaras can you retest perhaps ?

**Comment by galbaras** [comment]
Looks OK now.
