### ISSUE TITLE
Quick Edit Field Values "Field Errors"

### ISSUE THREAD

**Issue by neomorina** [wp-e-commerce/WP-e-Commerce#2155]
At WP e-Commerce new update,the products at quick edit does not auto-populate the fields Stock, Price, Sale Price, SKU, and Weight.

**Comment by misulicus** [comment]
@neomorina just sent a change that should get that fixed

https://github.com/wp-e-commerce/WP-e-Commerce/commit/b137765bd342262b2ade307c7f65829a0bec96c7
