### ISSUE TITLE
 Email error | fatal error

### ISSUE THREAD

**Issue by AppoPro** [wp-e-commerce/WP-e-Commerce#2156]
We have this error some one can help ?

WP eCommerce: 3.11.3
WP: 4.6.1

https://wordpress.org/support/topic/email-error-5/
https://wordpress.org/support/topic/check-out-fatal-error/
https://wordpress.org/support/topic/vfb-error-after-submit/

**Comment by misulicus** [comment]
Hey there,
Is the error still showing ?

**Comment by misulicus** [comment]
@AppoPro can you add the code change in this commit and retest ?
https://github.com/wp-e-commerce/WP-e-Commerce/commit/2253a0da98052025fe44e2750e456994fe631601

**Comment by misulicus** [comment]
This is resolved in latest release as of https://github.com/wp-e-commerce/WP-e-Commerce/commit/2253a0da98052025fe44e2750e456994fe631601
