### ISSUE TITLE
TEv2 Custom gateway fields visibility

### ISSUE THREAD

**Issue by misulicus** [wp-e-commerce/WP-e-Commerce#2158]
For custom gateways not in core (tested) that use different checkout fields like credit card fields there is an issue where the fields are always visible when there is a free cart.

Possible fix is wrapping this code inside the check below

```
if ( ! wpsc_is_free_cart() ) {
}
```

https://github.com/wp-e-commerce/WP-e-Commerce/blob/529913897bc76edff32eecde2b01197b8c4753a4/wpsc-components/merchant-core-v3/classes/payment-gateway.php#L466-L524

**Comment by JustinSainton** [comment]
@misulicus Might we be good to go here? I have Square installed and this seems to be a non-issue: https://cloudup.com/c4Dl0oRmbbh

**Comment by mihaijoldis** [comment]
Looks good so far ! Closing
