### ISSUE TITLE
Style purchase receipt pages

### ISSUE THREAD

**Issue by misulicus** [wp-e-commerce/WP-e-Commerce#2202]
We need some styling on the purchase receipt pages after customers purchase and the review order page

**Comment by JustinSainton** [comment]
With Express Checkout, if you have an order that requires shipping, the Review Order view you are taken to is terrible - just an unordered list for the address.  It should be a properly styled address.

https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-components/merchant-core-v3/gateways/paypal-express-checkout.php#L516-L543
