### ISSUE TITLE
Theme Engine V2: Ensure External Links are followed

### ISSUE THREAD

**Issue by JustinSainton** [wp-e-commerce/WP-e-Commerce#2206]
They currently are not.

**Comment by misulicus** [comment]
When a product has External link set we should show a Details/Buy now button instead of the Add to cart which actually adds the product to cart when clicked.

**Comment by JustinSainton** [comment]
Merged, seems to be fixed as of 0f59331273a3c9620eb5fe67ae2d8a8b408845d8
