### ISSUE TITLE
`wp-e-commerce` not always added to checkout body tag (TE1)

### ISSUE THREAD

**Issue by benhuson** [wp-e-commerce/WP-e-Commerce#2208]
On the checkout page the following two classes should be added to the body tag:

 - `wp-e-commerce`
 - `wpsc-shopping-cart`

I encountered an issue where if the checkout page could be accessed over https OR http, only one of them would be styled correctly.

I traced the issue back to the two classes above not being added in one of those scenarios.

I checked how those classes were added and traced it back to here:
https://github.com/wp-e-commerce/WP-e-Commerce/blob/master/wpsc-components/theme-engine-v1/helpers/template.php#L173

The classes are only added if `get_option( 'shopping_cart_url' ) == $page_url`

In my scenario `shopping_cart_url` was an https URL, so the classes were't added if I accessed the page at http.

Think this check should work for both the https and http version of the `shopping_cart_url` URL.

I suspect this would also affect `transact_url` and `user_account_url` body classes (which are a little further down in the code).

**Comment by JustinSainton** [comment]
Ah, good catch! I imagine perhaps using set_url_scheme() here would be an elegant enough approach, e.g. `set_url_scheme( $page_url, 'relative ) === set_url_scheme( get_option( $option ), 'relative' )`

What do you think of that? PR?

**Comment by benhuson** [comment]
That looks like it should work.

Wasn't aware of the `set_url_scheme` function - very handy.  
I'll have to add that to my list of "things I learned from Justin" which includes `wp_list_pluck` and `wp_list_filter` - awesome 😄

**Comment by JustinSainton** [comment]
@benhuson Can you confirm this to be resolved as of 56a7149?
