### ISSUE TITLE
JavaScript Error: TEV2, 2017

### ISSUE THREAD

**Issue by JustinSainton** [wp-e-commerce/WP-e-Commerce#2240]
Uncaught TypeError: Cannot read property 'top' of undefined
http://paleo-plan.dev/wp-content/themes/twentyseventeen/assets/js/global.js?ver=1.0 line 124

Not sure if related to us or 2017

**Comment by jtsternberg** [comment]
For reference: https://github.com/WordPress/twentyseventeen/blob/master/assets/js/global.js#L124

but that line 124 does not call `.top`. Maybe add a gist of your global.js for reference?

**Comment by JustinSainton** [comment]
https://github.com/WordPress/twentyseventeen/blob/master/assets/js/global.js#L116 <-- that's my line 124

**Comment by JustinSainton** [comment]
Update: Our checkout page has no `#secondary` div - so $sidebar would indeed not have an offset().

**Comment by JustinSainton** [comment]
Closing, as this is not our problem.
