### ISSUE TITLE
WordPress Plugin Management Select All Checkbox Broken by Sputnik.

### ISSUE THREAD

**Issue by JeffPyeBrook** [wp-e-commerce/WP-e-Commerce#2275]
It appears that the select all checkbox on the WordPress admin screen can be broken by something the marketplace" module is doing. Have seen this issue on two sites already.

Commenting out the include (shown below) of the module makes the issue go away.
```
//add_action( 'wpsc_includes', 'wpsc_beta_marketplace_bootstrap', 12 );

function wpsc_beta_marketplace_bootstrap() {
	if ( ! class_exists( 'Sputnik' ) ) {
		require_once( dirname( __FILE__ ) . '/library/Sputnik.php' );
		Sputnik::$path = dirname( __FILE__ );
		Sputnik::bootstrap();
	}
}
```

**Comment by misulicus** [comment]
Yep we know about it. We got a fix https://github.com/wp-e-commerce/WP-e-Commerce/issues/2209
Gonna have a 3.12.0 release in a few days.
