### ISSUE TITLE
Bug: Grid default to 4 not set

### ISSUE THREAD

**Issue by lizkaraffa** [wp-e-commerce/WP-e-Commerce#2290]
When a store is first setup, layout is to default to grid with 4 products per row. However in the customizer, the dropdown is blank https://cloudup.com/cEDx_PUAa3a the first time you view it. The class `wpsc-columns-4` is what styles the grid properly. However the class `wpsc-columns-auto` is appended on the products even though nothing in the codebase supports this anymore. Once a user sets the products per row the first time, everything gets fixed. We need the set defaults to work before there is any user interaction.

Code for this is on `bug/customizer-grid-default` branch.

**Comment by JustinSainton** [comment]
@lizkaraffa @misulicus Seems this has been resolved?

**Comment by mihaijoldis** [comment]
Yep
