### ISSUE TITLE
Placeholder text set as INPUT values in Theme Engine v2

### ISSUE THREAD

**Issue by leewillis77** [wp-e-commerce/WP-e-Commerce#2298]
On branch-4.0.0 it seems that the placeholder values for the checkout forms aren't using raw HTML placeholder attributes, but a Javascript-based solution. There are issues with this because the placeholder text seems to get set as the input field's value. 

To reproduce:
* Fresh install of branch-4.0.0
* Add an item to your cart, and head to checkout
* Without filling in any fields, open Chrome dev tools JS console, and run:
```
jQuery('#wpsc-checkout-field-billingfirstname-control').val()
```

*Expected behaviour:*
Empty string returned

*Actual behaviour:*
"First name" returned.

That seems odd and will cause issues with anything that integrates with the checkout fields via JS.

**Comment by JustinSainton** [comment]
@leewillis77 Good report! My _hunch_ is that this was introduced when the floating label functionality was introduced. If that's the case, we'll need to address this for sure.

@lizkaraffa Let me know if you can confirm and resolve. Thanks!

**Comment by mihaijoldis** [comment]
lee is right here. If you go to a checkout page for the first time and don't enter any info in the fields most of them will be "validated" since they do have a value of the placeholder which is wrong.
You could receive an order for customer FIrst Name Last Name

**Comment by JustinSainton** [comment]
"Lee is right here".

^ story of my life.

**Comment by leewillis77** [comment]
Being right in hindsight is easy ;)

**Comment by lizkaraffa** [comment]
Ok I think this fixed the issue. https://github.com/wp-e-commerce/WP-e-Commerce/tree/bug/form-placeholders good catch @leewillis77

**Comment by JustinSainton** [comment]
Merged, and seems to be working as expected!
