### ISSUE TITLE
PHP Warning: Illegal string offset 'products' in wpsc-includes/purchase-log.class.php on line 354

### ISSUE THREAD

**Issue by galbaras** [wp-e-commerce/WP-e-Commerce#2349]
As you can see [here](https://github.com/wp-e-commerce/WP-e-Commerce/blob/branch-4.0.0/wpsc-includes/purchase-log.class.php#L354), the array reference is used for an assignment, which is very strange indeed:

`			$args['products'] = array( $product );`

**Comment by galbaras** [comment]
@JustinSainton Any reason you've closed this issue?

**Comment by JustinSainton** [comment]
Fixed in the 3.15.0 branch
