### ISSUE TITLE
WP e-Commerce and theme Storefront Echo

### ISSUE THREAD

**Issue by ralphyke** [wp-e-commerce/WP-e-Commerce#2360]
Hello

I recently upgraded WP e-Commerce from 3.8.14.4 to the latest 3.13.1 (site bis-space.com/eshop)

All seemed fine but shortly after upgrading I realised that the functionality which opens a java script popup when you click "Add to Basket" no longer pops-up and then doesn't update the value of the basket on the page you are on.  However, if you click on the Basket and go to the checkout page, the item is there and the total has been updated.

So it is a problem with calling the popup and I've looked into the code (in particular wpsc-single_product.php which is in my Theme directory which is therefore from the older version) but cannot see anything that I think could cause the problem.

It's a bit of a long shot but doesn't anyone know of any of the major changes between these versions that might have caused this?

Thanks
Ralph

**Comment by mihaijoldis** [comment]
Hey there,
Make sure you have Display fancy purchase notifications enabled int he Store -> Presentation page.
Reopen this issue if that still does not work (but it should)
