### ISSUE TITLE
Support refunds

### ISSUE THREAD

**Issue by ace-dent** [wp-e-commerce/WP-e-Commerce#307]
We should have the ability to partly or fully refund an order.
Originally discussed here:
https://code.google.com/p/wp-e-commerce/issues/detail?id=335

Integration with Payment Gateways in my mind is secondary (but certainly nice to have). Basic facility to add a refund against an order - like an additional coupon discount, would be an amazing start. Then we have a chance of reconciling sales logs vs income when doing business accounts :)

**Comment by JustinSainton** [comment]
Assigning to @omarabid for 4.1.  @omarabid, let me know if you think you can tackle this for that cycle.

**Comment by omarabid** [comment]
@JustinSainton What's the date range for 4.1?

**Comment by JustinSainton** [comment]
@omarabid I'd like to ship 4.1 no later than the end of August.

**Comment by JustinSainton** [comment]
This is actually complete in master now, as of #2185. The API can definitely mature a bit, but as a part of a separate ticket.
