### ISSUE TITLE
Add cart messages when try to add more/less than max/min quantities to cart

### ISSUE THREAD

**Issue by benhuson** [wp-e-commerce/WP-e-Commerce#541]
Related to previous committed functionality in https://github.com/wp-e-commerce/WP-e-Commerce/issues/49 and https://github.com/wp-e-commerce/WP-e-Commerce/issues/219

Would be nice if a user tries to add more than the maximum allow quantity to cart they automatically get shown a message (like the out of stock message I imagine).

Similarly, if a minimum quantity is set the user should be notified if they do not add enough to their cart. It should probably also not add any items to cart if the minimum threshold is not met - current it rounds it up to meet that quota.

**Comment by JustinSainton** [comment]
Fixed for TEv2.  Not recommending that we necessarily fix it for v1, but if someone feels passionately about that, I'd merge a PR for it.

**Comment by JustinSainton** [comment]
Also, FWIW, not at all over the moon about how validation is being handled inside the cart controller in V2.  Could use a bit of cleanup.
