### ISSUE TITLE
Reëvaluate core gateways

### ISSUE THREAD

**Issue by JustinSainton** [wp-e-commerce/WP-e-Commerce#603]
The payment gateway landscape looks drastically different today than it did 7 years ago, when WPeC was first released.

Naturally, we'll need to remove Google Checkout from core sometime soon.  Why we still have ChronoPay in core, I honestly have no idea.  Probably time to spin that out separately.

Also, might be time to consider beefing up our test gateway a bit as well as considering  other gateways for core.  This ticket is just a placeholder for this larger conversation.

**Comment by omarabid** [comment]
@JustinSainton 

I think only PayPal Standard (and maybe Express) should be in core. The others should be either 1. paid or 2. free in a separate plugin. It might be a better idea to keep the old (v 2.0) gateways until we fully transition to v3.0 and remove that API completely from core.

**Comment by JustinSainton** [comment]
Closing this out for 4.0  The only actionable item here is likely removing Chronopay, which can be on a separate ticket.
